from typing import Union, Tuple, Optional

from xddtools.base import BaseID


class Colour(BaseID):
    def __init__(
            self,
            name: str,
            rgba: Union[str, Tuple[int, int, int, int], None] = None,
            hvec4: Optional[Tuple[float, float, float, float]] = None,
            shared_id: Optional[str] = None,
            darkness: Optional[float] = None,
            saturation: Optional[float] = None,
            default: Optional[str] = None,
    ):
        non_none_count = sum([rgba is not None, hvec4 is not None, shared_id is not None])
        non_none_count2 = sum([darkness is not None, saturation is not None])
        if non_none_count != 1 and non_none_count2 == 0:
            raise ValueError("Exactly one of 'rgba', 'hvec4', or 'shared_id' must be provided."
                             "If not,'darkness or 'saturation' must be provided.")
        if rgba is not None and isinstance(rgba, (tuple, list)) and len(rgba) != 4:
            raise ValueError("rgba must be a tuple of length 4")
        if hvec4 is not None and isinstance(hvec4, (tuple, list)) and len(hvec4) != 4:
            raise ValueError("hvec4 must be a tuple of length 4")
        self.rgba = rgba
        self.hvec4 = hvec4
        self.shared_id = shared_id
        self.darkness = darkness
        self.saturation = saturation
        self.default = default
        super().__init__(name=name)

    def __str__(self):
        res = [f'colour: .id "{self.id}"']
        if self.shared_id is not None:
            res.append(f'.shared_id "{self.shared_id}"')
        if self.rgba is not None:
            if isinstance(self.rgba, (tuple, list)):
                rgba = f"{self.rgba[0]} {self.rgba[1]} {self.rgba[2]} {self.rgba[3]}"
            else:
                rgba = f"{self.rgba}"
            res.append(f'.rgba {rgba}')
        if self.hvec4 is not None:
            if isinstance(self.hvec4, (tuple, list)):
                hvec4 = f"{self.hvec4[0]} {self.hvec4[1]} {self.hvec4[2]} {self.hvec4[3]}"
            else:
                hvec4 = f"{self.hvec4}"
            res.append(f'.hvec4 {hvec4}')
        if self.darkness is not None:
            res.append(f'.darkness {self.darkness}')
        if self.saturation is not None:
            res.append(f'.saturation {self.saturation}')
        return " ".join(res) + "\n"

    def __call__(self, text: Optional[str] = None) -> str:
        if text is None:
            if self.default is not None:
                text = self.default
            else:
                raise ValueError("No default text provided")
        if text.endswith("%"):
            text += " "
        return f"{{colour_start|{self.id}}}{text}{{colour_end}}"


# base._colours.darkest
button_highlight = Colour(name="button_highlight", hvec4=(1.5, 1.5, 1.3, 1.0))
red = Colour(name="red", rgba="#ff3a3a")
blue = Colour(name="blue", rgba="#2364c6")
green = Colour(name="green", rgba="#6be042")
yellow = Colour(name="yellow", rgba="#f8d047")
white = Colour(name="white", rgba=(255, 255, 255, 255))
neutral = Colour(name="neutral", rgba=(174, 172, 162, 255))
notable = Colour(name="notable", rgba=(200, 180, 110, 255))
harmful = Colour(name="harmful", rgba=(177, 25, 0, 255))
stress = Colour(name="stress", rgba="#e0ddce", default="压力")
stun = Colour(name="stun", rgba="#c99c45", default="眩晕")
move = Colour(name="move", rgba="#4c8ba2", default="位移")
blight = Colour(name="blight", rgba="#bdc241", default="腐蚀")
bleed = Colour(name="bleed", rgba="#b10000", default="流血")
debuff = Colour(name="debuff", rgba="#c3630f", default="减益")
buff = Colour(name="buff", rgba="#5ec9d6", default="增益自身：")
mark = Colour(name="mark", rgba="#b10000", default="标记")
deathdoor = Colour(name="deathdoor", rgba="#b10000", default="濒死")
deathblow = Colour(name="deathblow", rgba="#b10000", default="致死")
# disease = Colour(name="disease", rgba=(177, 25, 0, 255), default="疾病")
virtue = Colour(name="virtue", rgba="#e0ddce", default="美德")
afflicted = Colour(name="afflicted", rgba=(177, 25, 0, 255), default="痛苦")
scouting = Colour(name="scouting", rgba="#55998b", default="侦察")
surprised = Colour(name="surprised", rgba="#55998b", default="惊慌")
riposte = Colour(name="riposte", rgba="#c3630f", default="反击")
guard = Colour(name="guard", rgba="#5ec9d6", default="守护")
specific_class = Colour(name="specificclass", rgba="#8d7b5f", default=r"[仅用于%s]")
knock_back = Colour(name="knockback", rgba="#4c8ba2", default="击退")
attack_type = Colour(name="attacktype", rgba="#8d7b5f", default="近战")  # 远程
trap = Colour(name="trap", rgba="#8860b2", default="陷阱")
heal_hp = Colour(name="healhp", rgba="#87c241", default="治疗")
mortal_debuff = Colour(name="mortaldebuff", rgba="#c3630f", default="重创减益")
stealth = Colour(name="stealth", rgba="#443f86", default="潜行")
miasma = Colour(name="miasma", rgba="#38ada8")
stress_not1 = Colour(name="stressNOT1", shared_id="stress", default="压力")
stun_not1 = Colour(name="stunNOT1", shared_id="stun")
move_not1 = Colour(name="moveNOT1", shared_id="move")
blight_not1 = Colour(name="blightNOT1", shared_id="blight")
bleed_not1 = Colour(name="bleedNOT1", shared_id="bleed")
debuff_not1 = Colour(name="debuffNOT1", shared_id="debuff")
buff_not1 = Colour(name="buffNOT1", shared_id="buff")
mark_not1 = Colour(name="markNOT1", shared_id="mark")
deathdoor_not1 = Colour(name="deathdoorNOT1", shared_id="deathdoor")
deathblow_not1 = Colour(name="deathblowNOT1", shared_id="deathblow")
disease_not1 = Colour(name="diseaseNOT1", shared_id="disease")
virtue_not1 = Colour(name="virtueNOT1", shared_id="virtue")
afflicted_not1 = Colour(name="afflictedNOT1", shared_id="afflicted")
scouting_not1 = Colour(name="scoutingNOT1", shared_id="scouting")
surprised_not1 = Colour(name="surprisedNOT1", shared_id="surprised")
riposte_not1 = Colour(name="riposteNOT1", shared_id="riposte")
guard_not1 = Colour(name="guardNOT1", shared_id="guard")
specific_class_not1 = Colour(name="specificclassNOT1", shared_id="specificclass")
help_bracket_text = Colour(name="help_bracket_text", shared_id="notable")
help_text = Colour(name="help_text", shared_id="neutral")
# help_panel_controls = Colour(name="help_panel_controls", shared_id="neutral")
inventory_amount = Colour(name="inventory_amount", shared_id="notable")
inventory_amount_unselectable = Colour(name="inventory_amount_unselectable", rgba="#5d5a50")
inventory_amount_deduct = Colour(name="inventory_amount_deduct", rgba=(177, 161, 108, 255))
inventory_selectable = Colour(name="inventory_selectable", rgba="#fff", saturation=1.0)
inventory_selected = Colour(name="inventory_selected", hvec4=(1.4, 1.4, 1.7, 1.0), saturation=1.0)
inventory_unselectable = Colour(name="inventory_unselectable", rgba="#666", saturation=0.2)
inventory_shift_click_remove_item = Colour(name="inventory_shift_click_remove_item", shared_id="harmful")
inventory_tooltip_gold_value = Colour(name="inventory_tooltip_gold_value", shared_id="notable")
torch_centre = Colour(name="torch_centre", rgba="#ff7a00")
torch_ends = Colour(name="torch_ends", rgba="#5f0400")
torch_reduce_tip = Colour(name="torch_reduce_tip", rgba=(70, 70, 70, 255))
torch_snuff_tip = Colour(name="torch_snuff_tip", rgba=(70, 70, 70, 255))
ability_invalid = Colour(name="ability_invalid", rgba=(70, 70, 70, 255))
bark_neutral = Colour(name="bark_neutral", shared_id="neutral")
bark_afflicted = Colour(name="bark_afflicted", shared_id="harmful")
bark_virtued = Colour(name="bark_virtued", shared_id="notable")
bark_cursed = Colour(name="bark_cursed", shared_id="harmful")
user_information_neutral = Colour(name="user_information_neutral", rgba=(143, 8, 0, 255))
curio_investigate_hand_disabled = Colour(name="curio_investigate_hand_disabled", rgba="#666", saturation=0.2)
curio_investigate_text = Colour(name="curio_investigate_text", shared_id="notable")
curio_investigate_tooltip = Colour(name="curio_investigate_tooltip", shared_id="neutral")
curio_pass_text = Colour(name="curio_pass_text", shared_id="neutral")
curio_pass_tooltip = Colour(name="curio_pass_tooltip", shared_id="neutral")
obstacle_investigate_text = Colour(name="obstacle_investigate_text", shared_id="neutral")
obstacle_investigate_tooltip = Colour(name="obstacle_investigate_tooltip", shared_id="neutral")
obstacle_pass_text = Colour(name="obstacle_pass_text", shared_id="neutral")
obstacle_pass_tooltip = Colour(name="obstacle_pass_tooltip", shared_id="neutral")
ancestor_obstacle_investigate_text = Colour(name="ancestor_obstacle_investigate_text", shared_id="neutral")
ancestor_obstacle_investigate_tooltip = Colour(name="ancestor_obstacle_investigate_tooltip", shared_id="neutral")
town_name = Colour(name="town_name", shared_id="notable")
town_progression_forward = Colour(name="town_progression_forward", shared_id="harmful")
town_navigation_button_unselected = Colour(name="town_navigation_button_unselected", darkness=0.8, saturation=0.2)
town_roster_portrait_selectable = Colour(name="town_roster_portrait_selectable", darkness=1.0, saturation=1.0)
town_roster_portrait_unselectable = Colour(name="town_roster_portrait_unselectable", darkness=0.4, saturation=0.2)
town_roster_name = Colour(name="town_roster_name", shared_id="notable")
town_roster_number = Colour(name="town_roster_number", shared_id="neutral")
town_roster_affliction = Colour(name="town_roster_affliction", rgba=(255, 255, 255, 255))
character_panel_name_normal = Colour(name="character_panel_name_normal", shared_id="notable")
character_panel_name_editing = Colour(name="character_panel_name_editing", rgba="#ece9dc")
character_panel_position_pips_title = Colour(name="character_panel_position_pips_title", shared_id="neutral")
character_panel_target_pips_title = Colour(name="character_panel_target_pips_title", shared_id="neutral")
character_panel_palette_number = Colour(name="character_panel_palette_number", shared_id="neutral")
character_panel_previous_next_tooltip = Colour(name="character_panel_previous_next_tooltip", shared_id="neutral")
character_panel_edit_disabled = Colour(name="character_panel_edit_disabled", darkness=0.4, saturation=0.0)
town_quest_select_dungeon_name = Colour(name="town_quest_select_dungeon_name", shared_id="notable")
town_quest_select_dungeon_level = Colour(name="town_quest_select_dungeon_level", shared_id="neutral")
town_quest_select_xp_bar_gradient_left = Colour(name="town_quest_select_xp_bar_gradient_left", rgba="#8e0300")
town_quest_select_xp_bar_gradient_right = Colour(name="town_quest_select_xp_bar_gradient_right", rgba="#eb1600")
town_quest_select_xp_bar_gradient_background = Colour(name="town_quest_select_xp_bar_gradient_background",
                                                      rgba=(0, 0, 0, 255))
town_quest_select_party_name = Colour(name="town_quest_select_party_name", shared_id="notable")
town_quest_select_party_name_default = Colour(name="town_quest_select_party_name_default", rgba="#5d5a50")
town_quest_name = Colour(name="town_quest_name", shared_id="notable")
town_quest_description = Colour(name="town_quest_description", shared_id="neutral")
town_quest_specifics = Colour(name="town_quest_specifics", shared_id="neutral")
town_quest_camping = Colour(name="town_quest_camping", shared_id="notable")
town_quest_camping_tooltip = Colour(name="town_quest_camping_tooltip", shared_id="neutral")
town_quest_goals = Colour(name="town_quest_goals", shared_id="neutral")
town_quest_goal_start_description = Colour(name="town_quest_goal_start_description", shared_id="neutral")
town_quest_rewards = Colour(name="town_quest_rewards", shared_id="notable")
town_quest_trinket_retention = Colour(name="town_quest_trinket_retention", shared_id="notable")
town_activity_name = Colour(name="town_activity_name", shared_id="notable")
town_activity_description = Colour(name="town_activity_description", shared_id="neutral")
caretaker_goal_type_heading = Colour(name="caretaker_goal_type_heading", shared_id="notable")
caretaker_goal_completed = Colour(name="caretaker_goal_completed", shared_id="notable")
caretaker_goal_not_completed = Colour(name="caretaker_goal_not_completed", shared_id="neutral")
town_currency_amount = Colour(name="town_currency_amount", shared_id="notable")
town_currency_cant_afford_amount = Colour(name="town_currency_cant_afford_amount", shared_id="harmful")
town_free = Colour(name="town_free", shared_id="notable")
town_action_banner_name = Colour(name="town_action_banner_name", shared_id="notable")
town_action_banner_help = Colour(name="town_action_banner_help", rgba="#333333")
town_action_verbose_title_text = Colour(name="town_action_verbose_title_text", shared_id="notable")
town_action_verbose_body_text = Colour(name="town_action_verbose_body_text", shared_id="neutral")
town_building_info = Colour(name="town_building_info", rgba="#5d5a50")
town_building_upgrade_verbose = Colour(name="town_building_upgrade_verbose", shared_id="neutral")
town_building_upgrade_title = Colour(name="town_building_upgrade_title", shared_id="notable")
town_building_upgrade_percent = Colour(name="town_building_upgrade_percent", shared_id="notable")
skill_selected = Colour(name="skill_selected", hvec4=(1.5, 1.5, 1.3, 1.0), saturation=1.0)
skill_selectable = Colour(name="skill_selectable", darkness=1.0, saturation=1.0)
skill_unselectable = Colour(name="skill_unselectable", darkness=0.4, saturation=0.0)
skill_pip_default = Colour(name="skill_pip_default", rgba="#3d3b38")
skill_pip_party = Colour(name="skill_pip_party", shared_id="notable")
skill_pip_monsters = Colour(name="skill_pip_monsters", shared_id="harmful")
town_activity_log_entry = Colour(name="town_activity_log_entry", shared_id="neutral")
town_activity_log_building_name = Colour(name="town_activity_log_building_name", shared_id="notable")
town_activity_log_character_name = Colour(name="town_activity_log_character_name", shared_id="notable")
town_activity_log_story = Colour(name="town_activity_log_story", shared_id="town_activity_log_entry")
town_activity_log_positive_result = Colour(name="town_activity_log_positive_result", shared_id="notable")
town_activity_log_negative_result = Colour(name="town_activity_log_negative_result", shared_id="harmful")
town_activity_log_week_title = Colour(name="town_activity_log_week_title", shared_id="notable")
town_activity_hero_slot_tooltip = Colour(name="town_activity_hero_slot_tooltip", shared_id="neutral")
town_statue_archive_entry = Colour(name="town_statue_archive_entry", shared_id="neutral")
town_statue_media_heading = Colour(name="town_statue_media_heading", shared_id="neutral")
town_statue_archive_locked_entry = Colour(name="town_statue_archive_locked_entry", darkness=0.4, saturation=0.2)
town_statue_quote = Colour(name="town_statue_quote", shared_id="notable")
lighting_none_base = Colour(name="lighting_none_base", rgba=(255, 255, 255, 255))
lighting_none_half = Colour(name="lighting_none_half", rgba=(200, 200, 200, 255))
lighting_none_edge = Colour(name="lighting_none_edge", rgba=(75, 75, 75, 255))
lighting_full_base = Colour(name="lighting_full_base", rgba=(255, 255, 255, 255))
lighting_full_half = Colour(name="lighting_full_half", rgba=(200, 200, 200, 255))
lighting_full_edge = Colour(name="lighting_full_edge", rgba=(75, 75, 75, 255))
resolve_gradient_bottom = Colour(name="resolve_gradient_bottom", rgba="#6d6a5e")
resolve_gradient_top = Colour(name="resolve_gradient_top", rgba="#aea996")
resolve_new = Colour(name="resolve_new", rgba=(255, 255, 255, 255))
resolve_number = Colour(name="resolve_number", rgba=(0, 0, 0, 255))
resolve_tooltip_level = Colour(name="resolve_tooltip_level", shared_id="neutral")
resolve_tooltip_xp = Colour(name="resolve_tooltip_xp", shared_id="neutral")
resolve_tooltip_affliction = Colour(name="resolve_tooltip_affliction", shared_id="harmful")
resolve_tooltip_additional = Colour(name="resolve_tooltip_additional", shared_id="neutral")
town_choice_activity_choice = Colour(name="town_choice_activity_choice", shared_id="notable")
town_choice_activity_selected_choice = Colour(name="town_choice_activity_selected_choice", rgba=(255, 0, 0, 255))
town_choice_activity_choice_tooltip = Colour(name="town_choice_activity_choice_tooltip", shared_id="neutral")
town_estate_title = Colour(name="town_estate_title", rgba="#5d5a50")
town_estate_title_navigation_unselectable = Colour(name="town_estate_title_navigation_unselectable", rgba="#666")
town_start_raid = Colour(name="town_start_raid", rgba=(177, 161, 108, 255))
upgrade_tree_tooltip_title = Colour(name="upgrade_tree_tooltip_title", shared_id="notable")
upgrade_tree_tooltip_body = Colour(name="upgrade_tree_tooltip_body", shared_id="neutral")
upgrade_tree_icon_not_purchased = Colour(name="upgrade_tree_icon_not_purchased", darkness=0.4, saturation=0.0)
upgrade_tree_prerequisite_not_purchased = Colour(name="upgrade_tree_prerequisite_not_purchased", shared_id="harmful")
error_not_localized = Colour(name="error_not_localized", rgba=(0, 255, 255, 255))
error_string_too_wide = Colour(name="error_string_too_wide", rgba=(255, 105, 180, 255))
town_character_name = Colour(name="town_character_name", shared_id="notable")
town_character_class = Colour(name="town_character_class", shared_id="neutral")
town_character_skill_level = Colour(name="town_character_skill_level", shared_id="notable")
town_character_title = Colour(name="town_character_title", shared_id="notable")
town_upgrade_tree_title = Colour(name="town_upgrade_tree_title", shared_id="notable")
raid_results_quest_title = Colour(name="raid_results_quest_title", shared_id="notable")
raid_results_quest_result_was_completed = Colour(name="raid_results_quest_result_was_completed", shared_id="notable")
raid_results_quest_result_was_not_completed_escape = Colour(name="raid_results_quest_result_was_not_completed_escape",
                                                            rgba=(0, 0, 0, 255))
raid_results_quest_result_was_not_completed_defeat = Colour(name="raid_results_quest_result_was_not_completed_defeat",
                                                            shared_id="harmful")
raid_results_quest_result_was_not_completed_regroup = Colour(name="raid_results_quest_result_was_not_completed_regroup",
                                                             shared_id="neutral")
raid_results_quest_inventory_title = Colour(name="raid_results_quest_inventory_title", shared_id="notable")
raid_results_party_gold_inventory_title = Colour(name="raid_results_party_gold_inventory_title", shared_id="notable")
raid_results_party_heirloom_inventory_title = Colour(name="raid_results_party_heirloom_inventory_title",
                                                     shared_id="notable")
raid_results_hero_name = Colour(name="raid_results_hero_name", shared_id="notable")
raid_results_hero_resolve_from_quest = Colour(name="raid_results_hero_resolve_from_quest", rgba="#b5af9c")
raid_results_gold_popup = Colour(name="raid_results_gold_popup", shared_id="notable")
raid_retreat_button_unselectable = Colour(name="raid_retreat_button_unselectable", darkness=0.4, saturation=0.2)
raid_retreat_tooltip = Colour(name="raid_retreat_tooltip", shared_id="neutral")
trap_announcement = Colour(name="trap_announcement", shared_id="harmful")
disarm_announcement = Colour(name="disarm_announcement", shared_id="notable")
scouting_text = Colour(name="scouting_text", shared_id="notable")
confirm_dialog_question = Colour(name="confirm_dialog_question", shared_id="neutral")
confirm_dialog_answer = Colour(name="confirm_dialog_answer", shared_id="neutral")
tray_health_bar_background_bottom = Colour(name="tray_health_bar_background_bottom", rgba=(45, 45, 45, 255))
tray_health_bar_background_top = Colour(name="tray_health_bar_background_top", rgba=(18, 18, 18, 255))
tray_health_bar_default_damage_bottom = Colour(name="tray_health_bar_default_damage_bottom", rgba="#a32a00")
tray_health_bar_default_damage_top = Colour(name="tray_health_bar_default_damage_top", rgba="#ffa500")
tray_health_bar_default_heal_bottom = Colour(name="tray_health_bar_default_heal_bottom", rgba="#004e21")
tray_health_bar_default_heal_top = Colour(name="tray_health_bar_default_heal_top", rgba="#00e500")
tray_health_bar_default_current_bottom = Colour(name="tray_health_bar_default_current_bottom", rgba="#150000")
tray_health_bar_default_current_top = Colour(name="tray_health_bar_default_current_top", rgba="#cd0000")
tray_health_bar_corpse_damage_bottom = Colour(name="tray_health_bar_corpse_damage_bottom", rgba="#808080")
tray_health_bar_corpse_damage_top = Colour(name="tray_health_bar_corpse_damage_top", rgba="#F0F0F0")
tray_health_bar_corpse_heal_bottom = Colour(name="tray_health_bar_corpse_heal_bottom", rgba="#808080")
tray_health_bar_corpse_heal_top = Colour(name="tray_health_bar_corpse_heal_top", rgba="#F0F0F0")
tray_health_bar_corpse_current_bottom = Colour(name="tray_health_bar_corpse_current_bottom", rgba="#202020")
tray_health_bar_corpse_current_top = Colour(name="tray_health_bar_corpse_current_top", rgba="#606060")
tray_status_bar_tooltip_health = Colour(name="tray_status_bar_tooltip_health", shared_id="harmful")
tray_status_bar_tooltip_stress = Colour(name="tray_status_bar_tooltip_stress", shared_id="neutral")
tray_status_bar_tooltip_turns_remaining = Colour(name="tray_status_bar_tooltip_turns_remaining", shared_id="neutral")
tray_icon_tooltip_positive = Colour(name="tray_icon_tooltip_positive", shared_id="notable")
tray_icon_tooltip_negative = Colour(name="tray_icon_tooltip_negative", shared_id="harmful")
pop_text_stress_reduce = Colour(name="pop_text_stress_reduce", rgba="#fdf8c7")
pop_text_outline_stress_reduce = Colour(name="pop_text_outline_stress_reduce", rgba="#7c663f")
pop_text_stress_damage = Colour(name="pop_text_stress_damage", rgba="#000000")
pop_text_outline_stress_damage = Colour(name="pop_text_outline_stress_damage", rgba="#c2c2c2")
pop_text_miss = Colour(name="pop_text_miss", rgba="#000000")
pop_text_outline_miss = Colour(name="pop_text_outline_miss", rgba="#9a988f")
pop_text_no_damage = Colour(name="pop_text_no_damage", rgba="#920400")
pop_text_outline_no_damage = Colour(name="pop_text_outline_no_damage", rgba="#1e0400")
pop_text_crit_damage = Colour(name="pop_text_crit_damage", rgba="#ff7100")
pop_text_outline_crit_damage = Colour(name="pop_text_outline_crit_damage", rgba="#480800")
pop_text_damage = Colour(name="pop_text_damage", rgba="#e30900")
pop_text_outline_damage = Colour(name="pop_text_outline_damage", rgba="#390000")
pop_text_deathblow = Colour(name="pop_text_deathblow", rgba="#ff7100")
pop_text_outline_deathblow = Colour(name="pop_text_outline_deathblow", rgba="#480800")
pop_text_death_avoided = Colour(name="pop_text_death_avoided", rgba="#920400")
pop_text_outline_death_avoided = Colour(name="pop_text_outline_death_avoided", rgba="#1e0400")
pop_text_resist = Colour(name="pop_text_resist", rgba="#000000")
pop_text_outline_resist = Colour(name="pop_text_outline_resist", rgba="#9a988f")
pop_text_disease_resist = Colour(name="pop_text_disease_resist", rgba="#000000")
pop_text_outline_disease_resist = Colour(name="pop_text_outline_disease_resist", rgba=(173, 201, 98, 255))
pop_text_pass = Colour(name="pop_text_pass", rgba="#000000")
pop_text_outline_pass = Colour(name="pop_text_outline_pass", rgba="#9a988f")
pop_text_hero_heal = Colour(name="pop_text_hero_heal", rgba="#4fcb4f")
pop_text_outline_hero_heal = Colour(name="pop_text_outline_hero_heal", rgba="#2a4416")
pop_text_hero_heal_crit = Colour(name="pop_text_hero_heal_crit", rgba="#54ff70")
pop_text_outline_hero_heal_crit = Colour(name="pop_text_outline_hero_heal_crit", rgba="#05644f")
pop_text_monster_heal = Colour(name="pop_text_monster_heal", rgba="#4fcb4f")
pop_text_outline_monster_heal = Colour(name="pop_text_outline_monster_heal", rgba="#2a4416")
pop_text_monster_heal_crit = Colour(name="pop_text_monster_heal_crit", rgba="#54ff70")
pop_text_outline_monster_heal_crit = Colour(name="pop_text_outline_monster_heal_crit", rgba="#05644f")
pop_text_buff = Colour(name="pop_text_buff", rgba="#79f8ff")
pop_text_outline_buff = Colour(name="pop_text_outline_buff", rgba="#127298")
pop_text_debuff = Colour(name="pop_text_debuff", rgba="#e26826")
pop_text_outline_debuff = Colour(name="pop_text_outline_debuff", rgba="#7f290b")
pop_text_stun = Colour(name="pop_text_stun", rgba="#f0cf5a")
pop_text_outline_stun = Colour(name="pop_text_outline_stun", rgba="#8e5b11")
pop_text_stun_clear = Colour(name="pop_text_stun_clear", rgba="#f0cf5a")
pop_text_outline_stun_clear = Colour(name="pop_text_outline_stun_clear", rgba="#8e5b11")
pop_text_poison = Colour(name="pop_text_poison", rgba="#c6ff57")
pop_text_outline_poison = Colour(name="pop_text_outline_poison", rgba="#545828")
pop_text_bleed = Colour(name="pop_text_bleed", rgba="#e30900")
pop_text_outline_bleed = Colour(name="pop_text_outline_bleed", rgba="#390000")
pop_text_cured = Colour(name="pop_text_cured", rgba="#fdf8c7")
pop_text_outline_cured = Colour(name="pop_text_outline_cured", rgba="#7c663f")
pop_text_cure_failed = Colour(name="pop_text_cure_failed", rgba="#e26826")
pop_text_outline_cure_failed = Colour(name="pop_text_outline_cure_failed", rgba="#7f290b")
pop_text_tagged = Colour(name="pop_text_tagged", rgba="#e30900")
pop_text_outline_tagged = Colour(name="pop_text_outline_tagged", rgba="#390000")
pop_text_riposte = Colour(name="pop_text_riposte", rgba="#e30900")
pop_text_outline_riposte = Colour(name="pop_text_outline_riposte", rgba="#390000")
pop_text_guard = Colour(name="pop_text_guard", rgba="#79f8ff")
pop_text_outline_guard = Colour(name="pop_text_outline_guard", rgba="#127298")
pop_text_guard_failed = Colour(name="pop_text_guard_failed", rgba="#e26826")
pop_text_outline_guard_failed = Colour(name="pop_text_outline_guard_failed", rgba="#7f290b")
pop_text_full = Colour(name="pop_text_full", rgba="#000000")
pop_text_outline_full = Colour(name="pop_text_outline_full", rgba="#9a988f")
pop_text_heart_attack = Colour(name="pop_text_heart_attack", rgba="#000000")
pop_text_outline_heart_attack = Colour(name="pop_text_outline_heart_attack", rgba="#ffffff")
pop_text_move_resist = Colour(name="pop_text_move_resist", rgba="#000000")
pop_text_outline_move_resist = Colour(name="pop_text_outline_move_resist", rgba="#79f8ff")
pop_text_debuff_resist = Colour(name="pop_text_debuff_resist", rgba="#000000")
pop_text_outline_debuff_resist = Colour(name="pop_text_outline_debuff_resist", rgba="#e26826")
pop_text_stun_resist = Colour(name="pop_text_stun_resist", rgba="#000000")
pop_text_outline_stun_resist = Colour(name="pop_text_outline_stun_resist", rgba="#f0cf5a")
pop_text_poison_resist = Colour(name="pop_text_poison_resist", rgba="#000000")
pop_text_outline_poison_resist = Colour(name="pop_text_outline_poison_resist", rgba="#c6ff57")
pop_text_bleed_resist = Colour(name="pop_text_bleed_resist", rgba="#000000")
pop_text_outline_bleed_resist = Colour(name="pop_text_outline_bleed_resist", rgba="#e30900")
pop_text_heal_failed = Colour(name="pop_text_heal_failed", rgba="#000000")
pop_text_outline_heal_failed = Colour(name="pop_text_outline_heal_failed", rgba="#4fcb4f")
pop_text_stress_dot = Colour(name="pop_text_stress_dot", rgba="#000000")
pop_text_outline_stress_dot = Colour(name="pop_text_outline_stress_dot", rgba="#c2c2c2")
pop_text_stress_dot_resist = Colour(name="pop_text_stress_dot_resist", rgba="#000000")
pop_text_outline_stress_dot_resist = Colour(name="pop_text_outline_stress_dot_resist", rgba="#c2c2c2")
pop_text_control_resist = Colour(name="pop_text_control_resist", rgba="#000000")
pop_text_outline_control_resist = Colour(name="pop_text_outline_control_resist", rgba="#9a988f")
pop_text_hp_heal_dot_onset = Colour(name="pop_text_hp_heal_dot_onset", rgba="#4fcb4f")
pop_text_outline_hp_heal_dot_onset = Colour(name="pop_text_outline_hp_heal_dot_onset", rgba="#2a4416")
pop_text_hp_heal_dot = Colour(name="pop_text_hp_heal_dot", rgba="#4fcb4f")
pop_text_outline_hp_heal_dot = Colour(name="pop_text_outline_hp_heal_dot", rgba="#2a4416")
pop_text_hp_heal_dot_crit = Colour(name="pop_text_hp_heal_dot_crit", rgba="#54ff70")
pop_text_outline_hp_heal_dot_crit = Colour(name="pop_text_outline_hp_heal_dot_crit", rgba="#05644f")
quirk_positive = Colour(name="quirk_positive", shared_id="notable")
quirk_negative = Colour(name="quirk_negative", shared_id="harmful")
quirk_singleton_positive = Colour(name="quirk_singleton_positive", shared_id="notable")
quirk_singleton_negative = Colour(name="quirk_singleton_negative", shared_id="harmful")
disease = Colour(name="disease", rgba=(121, 141, 69, 255), default="疾病")
quirk_new_pulse_to = Colour(name="quirk_new_pulse_to", shared_id="neutral")
quirk_tooltip_description = Colour(name="quirk_tooltip_description", shared_id="neutral")
equipment_level = Colour(name="equipment_level", shared_id="neutral")
equipment_tooltip_title = Colour(name="equipment_tooltip_title", shared_id="notable")
equipment_tooltip_body = Colour(name="equipment_tooltip_body", shared_id="neutral")
resistance_name = Colour(name="resistance_name", shared_id="neutral")
resistance_value = Colour(name="resistance_value", shared_id="neutral")
campaign_status_affliction = Colour(name="campaign_status_affliction", shared_id="neutral")
raid_quest_info_complete = Colour(name="raid_quest_info_complete", shared_id="notable")
raid_quest_info_name = Colour(name="raid_quest_info_name", shared_id="notable")
raid_quest_info_goals = Colour(name="raid_quest_info_goals", shared_id="neutral")
town_quest_difficulty_1 = Colour
town_quest_difficulty_3 = Colour(name="town_quest_difficulty_3", rgba=(233, 170, 98, 255))
town_quest_difficulty_5 = Colour(name="town_quest_difficulty_5", rgba=(255, 87, 49, 255))
town_quest_difficulty_6 = Colour(name="town_quest_difficulty_6", shared_id="harmful")
trinket_hero_class_requirement = Colour(name="trinket_hero_class_requirement", shared_id="notable")
realm_inventory_trinket_sell_description = Colour(name="realm_inventory_trinket_sell_description", shared_id="notable")
realm_inventory_trinket_sell_instruction = Colour(name="realm_inventory_trinket_sell_instruction", shared_id="neutral")
provision_sell_back_info = Colour(name="provision_sell_back_info", rgba="#5d5a50")
provision_quest_info_dungeon_name = Colour(name="provision_quest_info_dungeon_name", shared_id="notable")
provision_quest_info_specs = Colour(name="provision_quest_info_specs", shared_id="neutral")
raid_loading_screen_title = Colour(name="raid_loading_screen_title", shared_id="notable")
raid_loading_screen_tip = Colour(name="raid_loading_screen_tip", shared_id="neutral")
town_screen_building_name = Colour(name="town_screen_building_name", shared_id="notable")
town_screen_building_description = Colour(name="town_screen_building_description", shared_id="neutral")
town_screen_colour_grade1 = Colour(name="town_screen_colour_grade1", rgba=(255, 255, 255, 255))
town_screen_colour_grade2 = Colour(name="town_screen_colour_grade2", rgba=(255, 255, 255, 255))
town_screen_colour_grade3 = Colour(name="town_screen_colour_grade3", rgba=(255, 255, 255, 255))
town_screen_colour_grade4 = Colour(name="town_screen_colour_grade4", rgba=(255, 255, 255, 255))
hero_slot_name = Colour(name="hero_slot_name", shared_id="notable")
quest_select_progress_xpbar_tooltip = Colour(name="quest_select_progress_xpbar_tooltip", shared_id="neutral")
quest_select_progress_town_event_icon_tooltip = Colour(name="quest_select_progress_town_event_icon_tooltip",
                                                       shared_id="neutral")
town_graveyard_story = Colour(name="town_graveyard_story", shared_id="neutral")
town_graveyard_hero_name = Colour(name="town_graveyard_hero_name", shared_id="notable")
town_graveyard_hero_death_week = Colour(name="town_graveyard_hero_death_week", rgba=(80, 79, 75, 255))
town_graveyard_death_count = Colour(name="town_graveyard_death_count", rgba=(134, 9, 2, 255))
town_activity_log_week_count = Colour(name="town_activity_log_week_count", shared_id="neutral")
town_statue_story = Colour(name="town_statue_story", shared_id="neutral")
kickstarter = Colour(name="kickstarter", rgba=(77, 191, 122, 255))
trophy = Colour(name="trophy", rgba=(222, 182, 105, 255))
ancestral = Colour(name="ancestral", rgba=(224, 39, 0, 255))
darkest_dungeon = Colour(name="darkest_dungeon", rgba=(224, 39, 0, 255))
ancestral_shambler = Colour(name="ancestral_shambler", rgba=(224, 39, 0, 255))
madman = Colour(name="madman", rgba=(224, 39, 0, 255))
courtier = Colour(name="courtier", rgba=(194, 69, 0, 255))
collector = Colour(name="collector", rgba=(241, 107, 4, 255))
uncommon = Colour(name="uncommon", rgba=(96, 149, 75, 255))
common = Colour(name="common", rgba=(168, 168, 168, 255))
very_common = Colour(name="very_common", rgba=(168, 168, 168, 255))
rare = Colour(name="rare", rgba=(59, 97, 167, 255))
very_rare = Colour(name="very_rare", rgba=(194, 69, 0, 255))
crow = Colour(name="crow", rgba=(224, 39, 0, 255))
roster_full = Colour(name="roster_full", shared_id="notable")
front_end_start_screen = Colour(name="front_end_start_screen", shared_id="notable")
front_end_build_number = Colour(name="front_end_build_number", rgba=(80, 80, 80, 255))
front_end_save_slot = Colour(name="front_end_save_slot", shared_id="notable")
front_end_save_slot_inactive = Colour(name="front_end_save_slot_inactive", rgba=(73, 71, 68, 255))
front_end_save_area = Colour(name="front_end_save_area", shared_id="neutral")
front_end_ticker = Colour(name="front_end_ticker", rgba=(73, 71, 68, 255))
front_end_preamble = Colour(name="front_end_preamble", shared_id="neutral")
front_end_campaign = Colour(name="front_end_campaign", shared_id="notable")
front_end_controls_element_text = Colour(name="front_end_controls_element_text", shared_id="neutral")
loading_screen_continue = Colour(name="loading_screen_continue", shared_id="neutral")
loading_screen_continue_pulse_to = Colour(name="loading_screen_continue_pulse_to", rgba=(200, 180, 110, 0))
tutorial_popup_title = Colour(name="tutorial_popup_title", shared_id="notable")
tutorial_popup_description = Colour(name="tutorial_popup_description", shared_id="neutral")
mailing_list_title = Colour(name="mailing_list_title", shared_id="notable")
mailing_list_description = Colour(name="mailing_list_description", shared_id="neutral")
mailing_list_answer = Colour(name="mailing_list_answer", shared_id="neutral")
journal_popup_title = Colour(name="journal_popup_title", shared_id="notable")
journal_popup_text = Colour(name="journal_popup_text", rgba=(21, 14, 5, 255))
journal_popup_count = Colour(name="journal_popup_count", rgba=(21, 14, 5, 255))
menu_base_element_text_base = Colour(name="menu_base_element_text_base", shared_id="neutral")
menu_base_element_text_highlight = Colour(name="menu_base_element_text_highlight", shared_id="notable")
menu_controls_category = Colour(name="menu_controls_category", shared_id="notable")
menu_controls_element = Colour(name="menu_controls_element", shared_id="neutral")
menu_options_element_name = Colour(name="menu_options_element_name", shared_id="neutral")
menu_options_element_name_disabled = Colour(name="menu_options_element_name_disabled", darkness=0.4, saturation=0.0)
menu_options_element_name_tooltip_cant_modify = Colour(name="menu_options_element_name_tooltip_cant_modify",
                                                       shared_id="harmful")
menu_options_element_name_tooltip = Colour(name="menu_options_element_name_tooltip", shared_id="neutral")
menu_options_element_control = Colour(name="menu_options_element_control", shared_id="neutral")
menu_options_element_control_disabled = Colour(name="menu_options_element_control_disabled", darkness=0.4,
                                               saturation=0.0)
menu_options_element_control_button = Colour(name="menu_options_element_control_button", rgba="#fff", saturation=1.0)
menu_options_element_control_button_disabled = Colour(name="menu_options_element_control_button_disabled", darkness=0.4,
                                                      saturation=0.0)
menu_options_require_restart = Colour(name="menu_options_require_restart", shared_id="harmful")
equipment_level_0 = Colour(name="equipment_level_0", rgba=(215, 213, 205, 255))
equipment_level_1 = Colour(name="equipment_level_1", rgba=(215, 213, 205, 255))
equipment_level_2 = Colour(name="equipment_level_2", rgba=(105, 190, 75, 255))
equipment_level_3 = Colour(name="equipment_level_3", rgba=(62, 114, 212, 255))
equipment_level_4 = Colour(name="equipment_level_4", shared_id="harmful")
loot_take_all_tooltip = Colour(name="loot_take_all_tooltip", shared_id="neutral")
loot_take_all_text = Colour(name="loot_take_all_text", shared_id="notable")
loot_close_tooltip = Colour(name="loot_close_tooltip", shared_id="neutral")
loot_close_text = Colour(name="loot_close_text", shared_id="notable")
event_hunger_eat_tooltip = Colour(name="event_hunger_eat_tooltip", shared_id="neutral")
event_hunger_eat_text = Colour(name="event_hunger_eat_text", shared_id="notable")
event_hunger_starve_tooltip = Colour(name="event_hunger_starve_tooltip", shared_id="neutral")
event_hunger_starve_text = Colour(name="event_hunger_starve_text", shared_id="notable")
round_display_number = Colour(name="round_display_number", shared_id="notable")
glossary_quote = Colour(name="glossary_quote", shared_id="notable")
glossary_term = Colour(name="glossary_term", shared_id="notable")
glossary_term_definition = Colour(name="glossary_term_definition", shared_id="neutral")
quest_info_camp_bonus_skill_tooltip = Colour(name="quest_info_camp_bonus_skill_tooltip", shared_id="notable")
quest_info_camp_bonus_skill_stats_tooltip = Colour(name="quest_info_camp_bonus_skill_stats_tooltip",
                                                   shared_id="neutral")
sanitarium_treatment_header = Colour(name="sanitarium_treatment_header", shared_id="notable")
sanitarium_treatment_entry = Colour(name="sanitarium_treatment_entry", shared_id="neutral")
sanitarium_treatment_positive_entry = Colour(name="sanitarium_treatment_positive_entry", shared_id="notable")
sanitarium_treatment_positive_entry_locked = Colour(name="sanitarium_treatment_positive_entry_locked", darkness=0.4,
                                                    saturation=0.2)
sanitarium_treatment_positive_entry_selected = Colour(name="sanitarium_treatment_positive_entry_selected",
                                                      shared_id="notable")
sanitarium_treatment_max_locked = Colour(name="sanitarium_treatment_max_locked", darkness=0.4, saturation=0.2)
sanitarium_treatment_negative_entry = Colour(name="sanitarium_treatment_negative_entry", shared_id="harmful")
sanitarium_treatment_negative_entry_locked = Colour(name="sanitarium_treatment_negative_entry_locked",
                                                    shared_id="harmful")
sanitarium_treatment_negative_entry_selected = Colour(name="sanitarium_treatment_negative_entry_selected",
                                                      shared_id="harmful")
sanitarium_treatment_disease_entry = Colour(name="sanitarium_treatment_disease_entry", rgba=(121, 141, 69, 255))
sanitarium_treatment_disease_entry_locked = Colour(name="sanitarium_treatment_disease_entry_locked",
                                                   shared_id="harmful")
sanitarium_treatment_disease_entry_selected = Colour(name="sanitarium_treatment_disease_entry_selected",
                                                     rgba=(173, 201, 98, 255))
monster_panel_monster_name = Colour(name="monster_panel_monster_name", shared_id="harmful")
monster_panel_monster_type = Colour(name="monster_panel_monster_type", shared_id="neutral")
monster_panel_monster_stats = Colour(name="monster_panel_monster_stats", shared_id="neutral")
monster_panel_hero_attack_stats = Colour(name="monster_panel_hero_attack_stats", shared_id="notable")
monster_panel_resistances_title = Colour(name="monster_panel_resistances_title", rgba="#5d5a50")
monster_panel_resistances_entry = Colour(name="monster_panel_resistances_entry", shared_id="neutral")
monster_panel_skills_title = Colour(name="monster_panel_skills_title", rgba="#5d5a50")
monster_panel_skills_entry = Colour(name="monster_panel_skills_entry", shared_id="neutral")
monster_panel_hp = Colour(name="monster_panel_hp", shared_id="harmful")
quest_complete_tooltip = Colour(name="quest_complete_tooltip", shared_id="neutral")
quest_complete_text = Colour(name="quest_complete_text", shared_id="notable")
realm_inventory_add_trinket_dialog_heading = Colour(name="realm_inventory_add_trinket_dialog_heading",
                                                    shared_id="neutral")
realm_inventory_add_trinket_dialog_edit_box = Colour(name="realm_inventory_add_trinket_dialog_edit_box",
                                                     shared_id="neutral")
stagecoach_add_hero_dialog_heading = Colour(name="stagecoach_add_hero_dialog_heading", shared_id="neutral")
stagecoach_add_hero_dialog_edit_box = Colour(name="stagecoach_add_hero_dialog_edit_box", shared_id="neutral")
stagecoach_empty_info_text = Colour(name="stagecoach_empty_info_text", shared_id="neutral")
stagecoach_prisoner_rescued = Colour(name="stagecoach_prisoner_rescued", shared_id="notable")
hero_slot_dimmed = Colour(name="hero_slot_dimmed", shared_id="town_roster_portrait_unselectable")
credits_category = Colour(name="credits_category", shared_id="notable")
credits_entry = Colour(name="credits_entry", shared_id="neutral")
credits_level_0 = Colour(name="credits_level_0", shared_id="notable")
credits_level_1 = Colour(name="credits_level_1", shared_id="notable")
credits_level_2 = Colour(name="credits_level_2", shared_id="neutral")
subtitle_context_raid = Colour(name="subtitle_context_raid", shared_id="notable")
subtitle_context_front_end = Colour(name="subtitle_context_front_end", shared_id="notable")
subtitle_context_loading_screen = Colour(name="subtitle_context_loading_screen", shared_id="notable")
subtitle_context_town = Colour(name="subtitle_context_town", shared_id="notable")
subtitle_context_movie = Colour(name="subtitle_context_movie", shared_id="notable")
subtitle_context_raid_results = Colour(name="subtitle_context_raid_results", shared_id="notable")
game_over_estate_name = Colour(name="game_over_estate_name", shared_id="notable")
game_over_estate_number_of_weeks = Colour(name="game_over_estate_number_of_weeks", shared_id="neutral")
game_over_estate_number_of_dead_heroes = Colour(name="game_over_estate_number_of_dead_heroes", shared_id="neutral")
game_over_estate_reason = Colour(name="game_over_estate_reason", shared_id="harmful")
town_event_story_title_bad = Colour(name="town_event_story_title_bad", shared_id="notable")
town_event_story_title_good = Colour(name="town_event_story_title_good", shared_id="notable")
town_event_story_title_neutral = Colour(name="town_event_story_title_neutral", shared_id="notable")
town_event_story_description = Colour(name="town_event_story_description", rgba=(21, 14, 5, 255))
town_event_info = Colour(name="town_event_info", shared_id="notable")
town_heirloom_exchange_title = Colour(name="town_heirloom_exchange_title", shared_id="notable")
town_heirloom_exchange_from_amount = Colour(name="town_heirloom_exchange_from_amount", shared_id="neutral")
town_heirloom_exchange_to_amount = Colour(name="town_heirloom_exchange_to_amount", shared_id="notable")
demo_message = Colour(name="demo_message", shared_id="notable")
help_panel_controls = Colour(name="help_panel_controls", shared_id="notable")
controls_panel_text = Colour(name="controls_panel_text", shared_id="notable")
controls_panel_title = Colour(name="controls_panel_title", shared_id="notable")
controls_panel_context_title = Colour(name="controls_panel_context_title", shared_id="notable")
controls_panel_button_description = Colour(name="controls_panel_button_description", shared_id="neutral")
controls_panel_context_title_text = Colour(name="controls_panel_context_title_text", shared_id="notable")
map_input_preview_pan = Colour(name="map_input_preview_pan", shared_id="neutral")
map_input_preview_zoom_in = Colour(name="map_input_preview_zoom_in", shared_id="neutral")
map_input_preview_zoom_out = Colour(name="map_input_preview_zoom_out", shared_id="neutral")
map_input_preview_reset = Colour(name="map_input_preview_reset", shared_id="neutral")
input_command_input_preview_text_default = Colour(name="input_command_input_preview_text_default", shared_id="neutral")
input_command_input_preview_saturation_fade_base = Colour(name="input_command_input_preview_saturation_fade_base",
                                                          rgba=(100, 100, 100, 255), saturation=0.0)
primary1 = Colour(name="primary1", rgba="#175190")
primary2 = Colour(name="primary2", rgba="#c82929")
secondary1 = Colour(name="secondary1", rgba="#9f43a1")
secondary2 = Colour(name="secondary2", rgba="#3bb265")
start1 = Colour(name="start1", shared_id="neutral")
start2 = Colour(name="start2", shared_id="neutral")
shoulder_l = Colour(name="shoulder_l", shared_id="neutral")
shoulder_r = Colour(name="shoulder_r", shared_id="neutral")
stick_l = Colour(name="stick_l", shared_id="neutral")
stick_r = Colour(name="stick_r", shared_id="neutral")
dpad_l = Colour(name="dpad_l", shared_id="neutral")
dpad_r = Colour(name="dpad_r", shared_id="neutral")
dpad_u = Colour(name="dpad_u", shared_id="neutral")
dpad_d = Colour(name="dpad_d", shared_id="neutral")
tpad_l = Colour(name="tpad_l", shared_id="neutral")
tpad_r = Colour(name="tpad_r", shared_id="neutral")
tpad = Colour(name="tpad", shared_id="neutral")
game_mode_select_dialog_question = Colour(name="game_mode_select_dialog_question", shared_id="notable")
game_mode_select_dialog_answers = Colour(name="game_mode_select_dialog_answers", shared_id="neutral")
game_mode_select_dialog_tooltip = Colour(name="game_mode_select_dialog_tooltip", shared_id="neutral")
save_slot_ugc_banner_text = Colour(name="save_slot_ugc_banner_text", shared_id="neutral")
user_generated_content_title_text = Colour(name="user_generated_content_title_text", shared_id="notable")
user_generated_content_sub_title_text = Colour(name="user_generated_content_sub_title_text", shared_id="neutral")
user_generated_content_entry_text = Colour(name="user_generated_content_entry_text", shared_id="notable")
user_generated_content_entry_tooltip = Colour(name="user_generated_content_entry_tooltip", shared_id="neutral")
user_generated_content_entry_tooltip_build = Colour(name="user_generated_content_entry_tooltip_build", darkness=0.4,
                                                    saturation=0.0)
town_district_entry_title_not_built = Colour(name="town_district_entry_title_not_built", shared_id="neutral")
town_district_entry_details_not_built = Colour(name="town_district_entry_details_not_built", darkness=0.4,
                                               saturation=0.0)
town_district_entry_title_built = Colour(name="town_district_entry_title_built", shared_id="notable")
town_district_entry_title_unavailable = Colour(name="town_district_entry_title_unavailable", darkness=0.4,
                                               saturation=0.0)
town_district_entry_details_built = Colour(name="town_district_entry_details_built", shared_id="neutral")
town_district_entry_details_unavailable = Colour(name="town_district_entry_details_unavailable", darkness=0.4,
                                                 saturation=0.0)
town_district_blueprint_tally = Colour(name="town_district_blueprint_tally", shared_id="notable")
town_district_cost_numbers = Colour(name="town_district_cost_numbers", shared_id="notable")
town_district_cost_numbers_insufficient = Colour(name="town_district_cost_numbers_insufficient", shared_id="harmful")
town_district_checkbox_disabled = Colour(name="town_district_checkbox_disabled", darkness=0.4, saturation=0.0)
town_district_tooltip = Colour(name="town_district_tooltip", shared_id="neutral")
save_slot_dlc_banner_text = Colour(name="save_slot_dlc_banner_text", rgba="#93844e")
save_slot_dlc_disabled_banner_text = Colour(name="save_slot_dlc_disabled_banner_text", shared_id="neutral")
downloadable_content_title_text = Colour(name="downloadable_content_title_text", shared_id="notable")
downloadable_content_sub_title_text = Colour(name="downloadable_content_sub_title_text", shared_id="neutral")
downloadable_content_entry_text = Colour(name="downloadable_content_entry_text", darkness=0.4, saturation=0.0)
downloadable_content_entry_tooltip = Colour(name="downloadable_content_entry_tooltip", shared_id="neutral")
downloadable_content_entry_tooltip_build = Colour(name="downloadable_content_entry_tooltip_build", darkness=0.5,
                                                  saturation=0.0)
downloadable_content_permanently_enabled_text = Colour(name="downloadable_content_permanently_enabled_text",
                                                       shared_id="notable")
downloadable_content_permanently_enabled_checkbox = Colour(name="downloadable_content_permanently_enabled_checkbox",
                                                           darkness=0.4, saturation=0.0)
downloadable_content_permanently_enabled_icon = Colour(name="downloadable_content_permanently_enabled_icon",
                                                       shared_id="white")
set_description_inactive = Colour(name="set_description_inactive", rgba="#555555")
set_description_active = Colour(name="set_description_active", rgba="#00ff00")
set_title = Colour(name="set_title", rgba="#84182d")
# town_event_tooltip = Colour(name="town_event_tooltip", shared_id="neutral")
singleton_quirk_tooltip_description = Colour(name="singleton_quirk_tooltip_description", shared_id="notable")
skip_curio_text = Colour(name="skip_curio_text", shared_id="notable")
wave_countdown_overlay_bar_bg_top = Colour(name="wave_countdown_overlay_bar_bg_top", rgba="#111111")
wave_countdown_overlay_bar_bg_bottom = Colour(name="wave_countdown_overlay_bar_bg_bottom", rgba="#333333")
wave_countdown_overlay_bar_top_left = Colour(name="wave_countdown_overlay_bar_top_left", rgba="#00d7a2")
wave_countdown_overlay_bar_top_right = Colour(name="wave_countdown_overlay_bar_top_right", rgba="#00d7a2")
wave_countdown_overlay_bar_bottom_left = Colour(name="wave_countdown_overlay_bar_bottom_left", rgba="#002438")
wave_countdown_overlay_bar_bottom_right = Colour(name="wave_countdown_overlay_bar_bottom_right", rgba="#002438")
wave_countdown_count = Colour(name="wave_countdown_count", rgba="#00d7a2")
wave_kill_count = Colour(name="wave_kill_count", rgba="#00d7a2")
wave_progress_tooltip_reward_tier_small = Colour(name="wave_progress_tooltip_reward_tier_small", shared_id="neutral")
wave_progress_tooltip_reward_tier_medium = Colour(name="wave_progress_tooltip_reward_tier_medium", rgba="#436b6b")
wave_progress_tooltip_reward_tier_large = Colour(name="wave_progress_tooltip_reward_tier_large", rgba="#5fc9af")
wave_progress_tooltip_reward_tier_wonderous = Colour(name="wave_progress_tooltip_reward_tier_wonderous", rgba="#f7e56f")
wave_skill_reset_announcement = Colour(name="wave_skill_reset_announcement", rgba="#a3ffee")
pop_text_guard_break = Colour(name="pop_text_guard_break", rgba="#f0cf5a")
pop_text_outline_guard_break = Colour(name="pop_text_outline_guard_break", rgba="#8e5b11")

# com._colours.darkest
# comet = Colour(name="comet", rgba="#a3ffee")
kill_counter_display_number = Colour(name="kill_counter_display_number", rgba="#C8B46E")
shard_escrow_number = Colour(name="shard_escrow_number", shared_id="comet")
mildred = Colour(name="mildred", rgba="#a3ffee")
shard_display_number = Colour(name="shard_display_number", rgba="#a3ffee")
raid_results_kill_counter = Colour(name="raid_results_kill_counter", rgba="#ff0000")
raid_results_kill_counter_tampered = Colour(name="raid_results_kill_counter_tampered", rgba="#ff6000")
raid_results_shard_number = Colour(name="raid_results_shard_number", rgba="#a3ffee")
raid_results_shard_inventory_title = Colour(name="raid_results_shard_inventory_title", rgba="#a3ffee")
raid_results_quest_result_endless = Colour(name="raid_results_quest_result_endless", rgba="#a3ffee")
town_quest_select_endless_wave_highscore = Colour(name="town_quest_select_endless_wave_highscore", rgba="#a3ffee")
town_quest_modifier_header = Colour(name="town_quest_modifier_header", shared_id="neutral")
town_quest_modifier_name = Colour(name="town_quest_modifier_name", rgba="#a3ffee")
pop_text_damage_reflect = Colour(name="pop_text_damage_reflect", rgba="#000000")
pop_text_outline_damage_reflect = Colour(name="pop_text_outline_damage_reflect", rgba=(200, 180, 110, 255))
pop_text_refresh_skills = Colour(name="pop_text_refresh_skills", rgba="#79f8ff")
pop_text_outline_refresh_skills = Colour(name="pop_text_outline_refresh_skills", rgba="#127298")
corpse_crystal_spawn_announcement = Colour(name="corpse_crystal_spawn_announcement", rgba="#a3ffee")
wave_log_kill_count = Colour(name="wave_log_kill_count", rgba="#a3ffee")
endless_highscore_title = Colour(name="endless_highscore_title", rgba="#49d5cd")
endless_highscore_killcount = Colour(name="endless_highscore_killcount", shared_id="comet")
endless_highscore_killcount_text = Colour(name="endless_highscore_killcount_text", shared_id="comet")
endless_highscore_killcount_tampered_text = Colour(name="endless_highscore_killcount_tampered_text", rgba="#ff6000")
endless_highscore_killcount_text_outline = Colour(name="endless_highscore_killcount_text_outline", rgba="#000000")
town_event_tooltip = Colour(name="town_event_tooltip", shared_id="neutral")
thing = Colour(name="thing", rgba="#4a929c")
memory = Colour(name="memory", shared_id="notable")

# crimson_court._colours.darkest
pop_text_vampire = Colour(name="pop_text_vampire", rgba="#000000")
pop_text_outline_vampire = Colour(name="pop_text_outline_vampire", rgba="#f40006")
pop_text_vampire_resist = Colour(name="pop_text_vampire_resist", rgba="#000000")
pop_text_outline_vampire_resist = Colour(name="pop_text_outline_vampire_resist", rgba="#9a988f")
pop_text_shuffle_dot = Colour(name="pop_text_shuffle_dot", rgba="#000000")
pop_text_outline_shuffle_dot = Colour(name="pop_text_outline_shuffle_dot", rgba="#79f8ff")
pop_text_shuffle_dot_resist = Colour(name="pop_text_shuffle_dot_resist", rgba="#000000")
pop_text_outline_shuffle_dot_resist = Colour(name="pop_text_outline_shuffle_dot_resist", rgba="#79f8ff")
pop_text_actor_dot_complete = Colour(name="pop_text_actor_dot_complete", rgba="#000000")
pop_text_outline_actor_dot_complete = Colour(name="pop_text_outline_actor_dot_complete", rgba="#fd0006")
quest_select_infestation_tooltip_verbose = Colour(name="quest_select_infestation_tooltip_verbose", shared_id="neutral")
quest_select_infestation_tooltip_description = Colour(name="quest_select_infestation_tooltip_description",
                                                      rgba=(177, 25, 0, 255))
quest_select_dungeon_estate_inventory_dependency_count_unmet = Colour(
    name="quest_select_dungeon_estate_inventory_dependency_count_unmet", shared_id="harmful")
quest_select_dungeon_estate_inventory_dependency_count_met = Colour(
    name="quest_select_dungeon_estate_inventory_dependency_count_met", shared_id="notable")
provision_infestation_quirk_evolution_death_hero_type = Colour(
    name="provision_infestation_quirk_evolution_death_hero_type", shared_id="neutral")
provision_infestation_quirk_evolution_death_hero_count = Colour(
    name="provision_infestation_quirk_evolution_death_hero_count", shared_id="harmful")
provision_infestation_quirk_evolution_death_hero_description = Colour(
    name="provision_infestation_quirk_evolution_death_hero_description", shared_id="neutral")
town_activity_building_contagion_description = Colour(name="town_activity_building_contagion_description",
                                                      shared_id="neutral")
town_activity_building_contagion_none = Colour(name="town_activity_building_contagion_none", shared_id="neutral")
town_activity_building_contagion_low = Colour(name="town_activity_building_contagion_low", rgba="#d9ab1d")
town_activity_building_contagion_medium = Colour(name="town_activity_building_contagion_medium", rgba="#e25500")
town_activity_building_contagion_high = Colour(name="town_activity_building_contagion_high", shared_id="harmful")
quirk_vampire = Colour(name="quirk_vampire", rgba="#f40006")
# crimson_court = Colour(name="crimson_court", shared_id="harmful")
blueprint = Colour(name="blueprint", shared_id="notable")

# shieldbreaker._colours.darkest
pop_text_health_damage_block_onset = Colour(name="pop_text_health_damage_block_onset", rgba="#000000")
pop_text_outline_health_damage_block_onset = Colour(name="pop_text_outline_health_damage_block_onset",
                                                    rgba=(200, 180, 110, 255))
pop_text_health_damage_block = Colour(name="pop_text_health_damage_block", rgba="#000000")
pop_text_outline_health_damage_block = Colour(name="pop_text_outline_health_damage_block", rgba=(200, 180, 110, 255))
pop_text_tag_block = Colour(name="pop_text_tag_block", rgba="#000000")
pop_text_outline_tag_block = Colour(name="pop_text_outline_tag_block", rgba=(200, 180, 110, 255))
shieldbreaker = Colour(name="shieldbreaker", rgba="#e0ddce")

# arena._colours.darkest
pop_text_daze = Colour(name="pop_text_daze", rgba="#f0cf5a")
pop_text_outline_daze = Colour(name="pop_text_outline_daze", rgba="#8e5b11")
pop_text_daze_resist = Colour(name="pop_text_daze_resist", rgba="#000000")
pop_text_outline_daze_resist = Colour(name="pop_text_outline_daze_resist", rgba="#f0cf5a")
arena = Colour(name="arena", shared_id="harmful")
founder = Colour(name="founder", rgba=(0, 255, 0, 255))
prize_booth_reward_locked_level = Colour(name="prize_booth_reward_locked_level", rgba=(177, 177, 177, 255))
prize_booth_reward_earned_level = Colour(name="prize_booth_reward_earned_level", shared_id="notable")
rankings_current_rank = Colour(name="rankings_current_rank", shared_id="notable")
rankings_next_rank = Colour(name="rankings_next_rank", rgba=(107, 107, 107, 255))
rankings_section_title = Colour(name="rankings_section_title", shared_id="notable")
rankings_stats = Colour(name="rankings_stats", rgba=(107, 107, 107, 255))
rankings_match_history_player = Colour(name="rankings_match_history_player", shared_id="notable")
rankings_match_history_opponent = Colour(name="rankings_match_history_opponent", shared_id="harmful")
rankings_match_history_vs = Colour(name="rankings_match_history_vs", shared_id="harmful")
rankings_leaderboards = Colour(name="rankings_leaderboards", shared_id="notable")
direct_challenge_friend = Colour(name="direct_challenge_friend", rgba=(177, 177, 177, 255))
matchmaking_time = Colour(name="matchmaking_time", rgba=(177, 177, 177, 255))
party_setup_title = Colour(name="party_setup_title", rgba=(177, 177, 177, 255))
party_setup_connection = Colour(name="party_setup_connection", rgba=(177, 177, 177, 255))
party_setup_message = Colour(name="party_setup_message", rgba=(177, 177, 177, 255))
reward_earned = Colour(name="reward_earned", rgba=(77, 191, 122, 255))
reward_locked = Colour(name="reward_locked", rgba=(177, 177, 177, 255))
reward_separator = Colour(name="reward_separator", rgba=(177, 177, 177, 255))
invite_sent = Colour(name="invite_sent", shared_id="notable")
results_desc = Colour(name="results_desc", shared_id="notable")
results_title = Colour(name="results_title", shared_id="harmful")
results_prestige = Colour(name="results_prestige", shared_id="notable")
results_prestige_dead_ally = Colour(name="results_prestige_dead_ally", rgba=(255, 0, 0, 255))
results_prestige_dead_enemy = Colour(name="results_prestige_dead_enemy", shared_id="notable")
results_prestige_inactive = Colour(name="results_prestige_inactive", rgba=(177, 177, 177, 255))
stalemate_lose = Colour(name="stalemate_lose", shared_id="harmful")
stalemate_win = Colour(name="stalemate_win", shared_id="notable")
crimson_court = Colour(name="crimson_court", shared_id="harmful")
comet = Colour(name="comet", rgba="#a3ffee")
league_novice = Colour(name="league_novice", rgba=(203, 203, 203, 255))
league_apprentice = Colour(name="league_apprentice", rgba=(96, 149, 75, 255))
league_veteran = Colour(name="league_veteran", rgba=(59, 97, 167, 255))
league_champion = Colour(name="league_champion", rgba=(194, 69, 0, 255))
league_darkest = Colour(name="league_darkest", rgba=(224, 39, 0, 255))
rank_display_tier = Colour(name="rank_display_tier", rgba=(203, 203, 203, 255))
party_builder_name_not_set = Colour(name="party_builder_name_not_set", rgba=(87, 87, 87, 255))
party_builder_name_set = Colour(name="party_builder_name_set", shared_id="notable")
party_builder_tooltip_desc = Colour(name="party_builder_tooltip_desc", rgba=(87, 87, 87, 255))
news_popup_title = Colour(name="news_popup_title", shared_id="notable")
news_popup_description = Colour(name="news_popup_description", shared_id="neutral")
