from typing import Union, Tuple, Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

from xddtools.base import ColourEntry, get_entry_id
from xddtools.name import AutoName


class Colour(ColourEntry, BaseModel):
    model_config = ConfigDict(frozen=True, strict=True, arbitrary_types_allowed=True)

    rgba: Union[str, Tuple[int, int, int, int], None] = None
    hvec4: Optional[Tuple[float, float, float, float]] = None
    shared_id: Optional[ColourEntry] = None
    darkness: Optional[float] = None
    saturation: Optional[float] = None
    default: Optional[str] = None
    entry_id: str = Field(default_factory=lambda x: AutoName().new_colour(), frozen=True)

    @model_validator(mode="after")
    def _check_after(self):
        non_none_count = sum([self.rgba is not None, self.hvec4 is not None, self.shared_id is not None])
        non_none_count2 = sum([self.darkness is not None, self.saturation is not None])
        if non_none_count != 1 and non_none_count2 == 0:
            raise ValueError("Exactly one of 'rgba', 'hvec4', or 'shared_id' must be provided."
                             "If not,'darkness or 'saturation' must be provided.")
        return self

    def __str__(self):
        res = [f'colour: .id "{self.id()}"']
        if self.shared_id is not None:
            res.append(f'.shared_id "{get_entry_id(self.shared_id)}"')
        if self.rgba is not None:
            if isinstance(self.rgba, (tuple, list)):
                rgba = f"{self.rgba[0]} {self.rgba[1]} {self.rgba[2]} {self.rgba[3]}"
            else:
                rgba = f"{self.rgba.lower()}"
            res.append(f'.rgba {rgba}')
        if self.hvec4 is not None:
            if isinstance(self.hvec4, (tuple, list)):
                hvec4 = f"{self.hvec4[0]} {self.hvec4[1]} {self.hvec4[2]} {self.hvec4[3]}"
            else:
                hvec4 = f"{self.hvec4}"
            res.append(f'.hvec4 {hvec4}')
        if self.darkness is not None:
            res.append(f'.darkness {self.darkness}')
        if self.saturation is not None:
            res.append(f'.saturation {self.saturation}')
        return " ".join(res)

    def __call__(self, text: Optional[str] = None) -> str:
        if text is None:
            if self.default is not None:
                text = self.default
            else:
                raise ValueError("No default text provided")
        if text.endswith("%"):
            text += " "
        return f"{{colour_start|{self.id()}}}{text}{{colour_end}}"


pink = Colour(entry_id="pink", rgba="#FFC0CB")
invisible = Colour(entry_id="invisible", rgba=(0, 0, 0, 0), default="")
# base._colours.darkest
button_highlight = Colour(entry_id="button_highlight", hvec4=(1.5, 1.5, 1.3, 1.0))
red = Colour(entry_id="red", rgba="#ff3a3a")
blue = Colour(entry_id="blue", rgba="#2364c6")
green = Colour(entry_id="green", rgba="#6be042")
yellow = Colour(entry_id="yellow", rgba="#f8d047")
white = Colour(entry_id="white", rgba=(255, 255, 255, 255))
neutral = Colour(entry_id="neutral", rgba=(174, 172, 162, 255))
notable = Colour(entry_id="notable", rgba=(200, 180, 110, 255))
harmful = Colour(entry_id="harmful", rgba=(177, 25, 0, 255))
stress = Colour(entry_id="stress", rgba="#e0ddce", default="压力")
stun = Colour(entry_id="stun", rgba="#c99c45", default="眩晕")
move = Colour(entry_id="move", rgba="#4c8ba2", default="位移")
blight = Colour(entry_id="blight", rgba="#bdc241", default="腐蚀")
bleed = Colour(entry_id="bleed", rgba="#b10000", default="流血")
debuff = Colour(entry_id="debuff", rgba="#c3630f", default="减益")
buff = Colour(entry_id="buff", rgba="#5ec9d6", default="增益自身：")
mark = Colour(entry_id="mark", rgba="#b10000", default="标记")
deathdoor = Colour(entry_id="deathdoor", rgba="#b10000", default="濒死")
deathblow = Colour(entry_id="deathblow", rgba="#b10000", default="致死")
# disease = Colour(entry_id="disease", rgba=(177, 25, 0, 255), default="疾病")
disease = Colour(entry_id="disease", rgba=(121, 141, 69, 255), default="疾病")
virtue = Colour(entry_id="virtue", rgba="#e0ddce", default="美德")
afflicted = Colour(entry_id="afflicted", rgba=(177, 25, 0, 255), default="痛苦")
scouting = Colour(entry_id="scouting", rgba="#55998b", default="侦察")
surprised = Colour(entry_id="surprised", rgba="#55998b", default="惊慌")
riposte = Colour(entry_id="riposte", rgba="#c3630f", default="反击")
guard = Colour(entry_id="guard", rgba="#5ec9d6", default="守护")
specific_class = Colour(entry_id="specificclass", rgba="#8d7b5f", default=r"[仅用于%s]")
knock_back = Colour(entry_id="knockback", rgba="#4c8ba2", default="击退")
attack_type = Colour(entry_id="attacktype", rgba="#8d7b5f", default="近战")  # 远程
trap = Colour(entry_id="trap", rgba="#8860b2", default="陷阱")
heal_hp = Colour(entry_id="healhp", rgba="#87c241", default="治疗")
mortal_debuff = Colour(entry_id="mortaldebuff", rgba="#c3630f", default="重创减益")
stealth = Colour(entry_id="stealth", rgba="#443f86", default="潜行")
miasma = Colour(entry_id="miasma", rgba="#38ada8")
stress_not1 = Colour(entry_id="stressNOT1", shared_id=stress, default="压力")
stun_not1 = Colour(entry_id="stunNOT1", shared_id=stun)
move_not1 = Colour(entry_id="moveNOT1", shared_id=move)
blight_not1 = Colour(entry_id="blightNOT1", shared_id=blight)
bleed_not1 = Colour(entry_id="bleedNOT1", shared_id=bleed)
debuff_not1 = Colour(entry_id="debuffNOT1", shared_id=debuff)
buff_not1 = Colour(entry_id="buffNOT1", shared_id=buff)
mark_not1 = Colour(entry_id="markNOT1", shared_id=mark)
deathdoor_not1 = Colour(entry_id="deathdoorNOT1", shared_id=deathdoor)
deathblow_not1 = Colour(entry_id="deathblowNOT1", shared_id=deathblow)
disease_not1 = Colour(entry_id="diseaseNOT1", shared_id=disease)
virtue_not1 = Colour(entry_id="virtueNOT1", shared_id=virtue)
afflicted_not1 = Colour(entry_id="afflictedNOT1", shared_id=afflicted)
scouting_not1 = Colour(entry_id="scoutingNOT1", shared_id=scouting)
surprised_not1 = Colour(entry_id="surprisedNOT1", shared_id=surprised)
riposte_not1 = Colour(entry_id="riposteNOT1", shared_id=riposte)
guard_not1 = Colour(entry_id="guardNOT1", shared_id=guard)
specific_class_not1 = Colour(entry_id="specificclassNOT1", shared_id=specific_class)
help_bracket_text = Colour(entry_id="help_bracket_text", shared_id=notable)
help_text = Colour(entry_id="help_text", shared_id=neutral)
# help_panel_controls = Colour(entry_id="help_panel_controls", shared_id=neutral)
inventory_amount = Colour(entry_id="inventory_amount", shared_id=notable)
inventory_amount_unselectable = Colour(entry_id="inventory_amount_unselectable", rgba="#5d5a50")
inventory_amount_deduct = Colour(entry_id="inventory_amount_deduct", rgba=(177, 161, 108, 255))
inventory_selectable = Colour(entry_id="inventory_selectable", rgba="#fff", saturation=1.0)
inventory_selected = Colour(entry_id="inventory_selected", hvec4=(1.4, 1.4, 1.7, 1.0), saturation=1.0)
inventory_unselectable = Colour(entry_id="inventory_unselectable", rgba="#666", saturation=0.2)
inventory_shift_click_remove_item = Colour(entry_id="inventory_shift_click_remove_item", shared_id=harmful)
inventory_tooltip_gold_value = Colour(entry_id="inventory_tooltip_gold_value", shared_id=notable)
torch_centre = Colour(entry_id="torch_centre", rgba="#ff7a00")
torch_ends = Colour(entry_id="torch_ends", rgba="#5f0400")
torch_reduce_tip = Colour(entry_id="torch_reduce_tip", rgba=(70, 70, 70, 255))
torch_snuff_tip = Colour(entry_id="torch_snuff_tip", rgba=(70, 70, 70, 255))
ability_invalid = Colour(entry_id="ability_invalid", rgba=(70, 70, 70, 255))
bark_neutral = Colour(entry_id="bark_neutral", shared_id=neutral)
bark_afflicted = Colour(entry_id="bark_afflicted", shared_id=harmful)
bark_virtued = Colour(entry_id="bark_virtued", shared_id=notable)
bark_cursed = Colour(entry_id="bark_cursed", shared_id=harmful)
user_information_neutral = Colour(entry_id="user_information_neutral", rgba=(143, 8, 0, 255))
curio_investigate_hand_disabled = Colour(entry_id="curio_investigate_hand_disabled", rgba="#666", saturation=0.2)
curio_investigate_text = Colour(entry_id="curio_investigate_text", shared_id=notable)
curio_investigate_tooltip = Colour(entry_id="curio_investigate_tooltip", shared_id=neutral)
curio_pass_text = Colour(entry_id="curio_pass_text", shared_id=neutral)
curio_pass_tooltip = Colour(entry_id="curio_pass_tooltip", shared_id=neutral)
obstacle_investigate_text = Colour(entry_id="obstacle_investigate_text", shared_id=neutral)
obstacle_investigate_tooltip = Colour(entry_id="obstacle_investigate_tooltip", shared_id=neutral)
obstacle_pass_text = Colour(entry_id="obstacle_pass_text", shared_id=neutral)
obstacle_pass_tooltip = Colour(entry_id="obstacle_pass_tooltip", shared_id=neutral)
ancestor_obstacle_investigate_text = Colour(entry_id="ancestor_obstacle_investigate_text", shared_id=neutral)
ancestor_obstacle_investigate_tooltip = Colour(entry_id="ancestor_obstacle_investigate_tooltip", shared_id=neutral)
town_name = Colour(entry_id="town_name", shared_id=notable)
town_progression_forward = Colour(entry_id="town_progression_forward", shared_id=harmful)
town_navigation_button_unselected = Colour(entry_id="town_navigation_button_unselected", darkness=0.8, saturation=0.2)
town_roster_portrait_selectable = Colour(entry_id="town_roster_portrait_selectable", darkness=1.0, saturation=1.0)
town_roster_portrait_unselectable = Colour(entry_id="town_roster_portrait_unselectable", darkness=0.4, saturation=0.2)
town_roster_name = Colour(entry_id="town_roster_name", shared_id=notable)
town_roster_number = Colour(entry_id="town_roster_number", shared_id=neutral)
town_roster_affliction = Colour(entry_id="town_roster_affliction", rgba=(255, 255, 255, 255))
character_panel_name_normal = Colour(entry_id="character_panel_name_normal", shared_id=notable)
character_panel_name_editing = Colour(entry_id="character_panel_name_editing", rgba="#ece9dc")
character_panel_position_pips_title = Colour(entry_id="character_panel_position_pips_title", shared_id=neutral)
character_panel_target_pips_title = Colour(entry_id="character_panel_target_pips_title", shared_id=neutral)
character_panel_palette_number = Colour(entry_id="character_panel_palette_number", shared_id=neutral)
character_panel_previous_next_tooltip = Colour(entry_id="character_panel_previous_next_tooltip", shared_id=neutral)
character_panel_edit_disabled = Colour(entry_id="character_panel_edit_disabled", darkness=0.4, saturation=0.0)
town_quest_select_dungeon_name = Colour(entry_id="town_quest_select_dungeon_name", shared_id=notable)
town_quest_select_dungeon_level = Colour(entry_id="town_quest_select_dungeon_level", shared_id=neutral)
town_quest_select_xp_bar_gradient_left = Colour(entry_id="town_quest_select_xp_bar_gradient_left", rgba="#8e0300")
town_quest_select_xp_bar_gradient_right = Colour(entry_id="town_quest_select_xp_bar_gradient_right", rgba="#eb1600")
town_quest_select_xp_bar_gradient_background = Colour(entry_id="town_quest_select_xp_bar_gradient_background",
                                                      rgba=(0, 0, 0, 255))
town_quest_select_party_name = Colour(entry_id="town_quest_select_party_name", shared_id=notable)
town_quest_select_party_name_default = Colour(entry_id="town_quest_select_party_name_default", rgba="#5d5a50")
town_quest_name = Colour(entry_id="town_quest_name", shared_id=notable)
town_quest_description = Colour(entry_id="town_quest_description", shared_id=neutral)
town_quest_specifics = Colour(entry_id="town_quest_specifics", shared_id=neutral)
town_quest_camping = Colour(entry_id="town_quest_camping", shared_id=notable)
town_quest_camping_tooltip = Colour(entry_id="town_quest_camping_tooltip", shared_id=neutral)
town_quest_goals = Colour(entry_id="town_quest_goals", shared_id=neutral)
town_quest_goal_start_description = Colour(entry_id="town_quest_goal_start_description", shared_id=neutral)
town_quest_rewards = Colour(entry_id="town_quest_rewards", shared_id=notable)
town_quest_trinket_retention = Colour(entry_id="town_quest_trinket_retention", shared_id=notable)
town_activity_name = Colour(entry_id="town_activity_name", shared_id=notable)
town_activity_description = Colour(entry_id="town_activity_description", shared_id=neutral)
caretaker_goal_type_heading = Colour(entry_id="caretaker_goal_type_heading", shared_id=notable)
caretaker_goal_completed = Colour(entry_id="caretaker_goal_completed", shared_id=notable)
caretaker_goal_not_completed = Colour(entry_id="caretaker_goal_not_completed", shared_id=neutral)
town_currency_amount = Colour(entry_id="town_currency_amount", shared_id=notable)
town_currency_cant_afford_amount = Colour(entry_id="town_currency_cant_afford_amount", shared_id=harmful)
town_free = Colour(entry_id="town_free", shared_id=notable)
town_action_banner_name = Colour(entry_id="town_action_banner_name", shared_id=notable)
town_action_banner_help = Colour(entry_id="town_action_banner_help", rgba="#333333")
town_action_verbose_title_text = Colour(entry_id="town_action_verbose_title_text", shared_id=notable)
town_action_verbose_body_text = Colour(entry_id="town_action_verbose_body_text", shared_id=neutral)
town_building_info = Colour(entry_id="town_building_info", rgba="#5d5a50")
town_building_upgrade_verbose = Colour(entry_id="town_building_upgrade_verbose", shared_id=neutral)
town_building_upgrade_title = Colour(entry_id="town_building_upgrade_title", shared_id=notable)
town_building_upgrade_percent = Colour(entry_id="town_building_upgrade_percent", shared_id=notable)
skill_selected = Colour(entry_id="skill_selected", hvec4=(1.5, 1.5, 1.3, 1.0), saturation=1.0)
skill_selectable = Colour(entry_id="skill_selectable", darkness=1.0, saturation=1.0)
skill_unselectable = Colour(entry_id="skill_unselectable", darkness=0.4, saturation=0.0)
skill_pip_default = Colour(entry_id="skill_pip_default", rgba="#3d3b38")
skill_pip_party = Colour(entry_id="skill_pip_party", shared_id=notable)
skill_pip_monsters = Colour(entry_id="skill_pip_monsters", shared_id=harmful)
town_activity_log_entry = Colour(entry_id="town_activity_log_entry", shared_id=neutral)
town_activity_log_building_name = Colour(entry_id="town_activity_log_building_name", shared_id=notable)
town_activity_log_character_name = Colour(entry_id="town_activity_log_character_name", shared_id=notable)
town_activity_log_story = Colour(entry_id="town_activity_log_story", shared_id=town_activity_log_entry)
town_activity_log_positive_result = Colour(entry_id="town_activity_log_positive_result", shared_id=notable)
town_activity_log_negative_result = Colour(entry_id="town_activity_log_negative_result", shared_id=harmful)
town_activity_log_week_title = Colour(entry_id="town_activity_log_week_title", shared_id=notable)
town_activity_hero_slot_tooltip = Colour(entry_id="town_activity_hero_slot_tooltip", shared_id=neutral)
town_statue_archive_entry = Colour(entry_id="town_statue_archive_entry", shared_id=neutral)
town_statue_media_heading = Colour(entry_id="town_statue_media_heading", shared_id=neutral)
town_statue_archive_locked_entry = Colour(entry_id="town_statue_archive_locked_entry", darkness=0.4, saturation=0.2)
town_statue_quote = Colour(entry_id="town_statue_quote", shared_id=notable)
lighting_none_base = Colour(entry_id="lighting_none_base", rgba=(255, 255, 255, 255))
lighting_none_half = Colour(entry_id="lighting_none_half", rgba=(200, 200, 200, 255))
lighting_none_edge = Colour(entry_id="lighting_none_edge", rgba=(75, 75, 75, 255))
lighting_full_base = Colour(entry_id="lighting_full_base", rgba=(255, 255, 255, 255))
lighting_full_half = Colour(entry_id="lighting_full_half", rgba=(200, 200, 200, 255))
lighting_full_edge = Colour(entry_id="lighting_full_edge", rgba=(75, 75, 75, 255))
resolve_gradient_bottom = Colour(entry_id="resolve_gradient_bottom", rgba="#6d6a5e")
resolve_gradient_top = Colour(entry_id="resolve_gradient_top", rgba="#aea996")
resolve_new = Colour(entry_id="resolve_new", rgba=(255, 255, 255, 255))
resolve_number = Colour(entry_id="resolve_number", rgba=(0, 0, 0, 255))
resolve_tooltip_level = Colour(entry_id="resolve_tooltip_level", shared_id=neutral)
resolve_tooltip_xp = Colour(entry_id="resolve_tooltip_xp", shared_id=neutral)
resolve_tooltip_affliction = Colour(entry_id="resolve_tooltip_affliction", shared_id=harmful)
resolve_tooltip_additional = Colour(entry_id="resolve_tooltip_additional", shared_id=neutral)
town_choice_activity_choice = Colour(entry_id="town_choice_activity_choice", shared_id=notable)
town_choice_activity_selected_choice = Colour(entry_id="town_choice_activity_selected_choice", rgba=(255, 0, 0, 255))
town_choice_activity_choice_tooltip = Colour(entry_id="town_choice_activity_choice_tooltip", shared_id=neutral)
town_estate_title = Colour(entry_id="town_estate_title", rgba="#5d5a50")
town_estate_title_navigation_unselectable = Colour(entry_id="town_estate_title_navigation_unselectable", rgba="#666")
town_start_raid = Colour(entry_id="town_start_raid", rgba=(177, 161, 108, 255))
upgrade_tree_tooltip_title = Colour(entry_id="upgrade_tree_tooltip_title", shared_id=notable)
upgrade_tree_tooltip_body = Colour(entry_id="upgrade_tree_tooltip_body", shared_id=neutral)
upgrade_tree_icon_not_purchased = Colour(entry_id="upgrade_tree_icon_not_purchased", darkness=0.4, saturation=0.0)
upgrade_tree_prerequisite_not_purchased = Colour(entry_id="upgrade_tree_prerequisite_not_purchased", shared_id=harmful)
error_not_localized = Colour(entry_id="error_not_localized", rgba=(0, 255, 255, 255))
error_string_too_wide = Colour(entry_id="error_string_too_wide", rgba=(255, 105, 180, 255))
town_character_name = Colour(entry_id="town_character_name", shared_id=notable)
town_character_class = Colour(entry_id="town_character_class", shared_id=neutral)
town_character_skill_level = Colour(entry_id="town_character_skill_level", shared_id=notable)
town_character_title = Colour(entry_id="town_character_title", shared_id=notable)
town_upgrade_tree_title = Colour(entry_id="town_upgrade_tree_title", shared_id=notable)
raid_results_quest_title = Colour(entry_id="raid_results_quest_title", shared_id=notable)
raid_results_quest_result_was_completed = Colour(entry_id="raid_results_quest_result_was_completed", shared_id=notable)
raid_results_quest_result_was_not_completed_escape = Colour(
    entry_id="raid_results_quest_result_was_not_completed_escape",
    rgba=(0, 0, 0, 255))
raid_results_quest_result_was_not_completed_defeat = Colour(
    entry_id="raid_results_quest_result_was_not_completed_defeat",
    shared_id=harmful)
raid_results_quest_result_was_not_completed_regroup = Colour(
    entry_id="raid_results_quest_result_was_not_completed_regroup",
    shared_id=neutral)
raid_results_quest_inventory_title = Colour(entry_id="raid_results_quest_inventory_title", shared_id=notable)
raid_results_party_gold_inventory_title = Colour(entry_id="raid_results_party_gold_inventory_title", shared_id=notable)
raid_results_party_heirloom_inventory_title = Colour(entry_id="raid_results_party_heirloom_inventory_title",
                                                     shared_id=notable)
raid_results_hero_name = Colour(entry_id="raid_results_hero_name", shared_id=notable)
raid_results_hero_resolve_from_quest = Colour(entry_id="raid_results_hero_resolve_from_quest", rgba="#b5af9c")
raid_results_gold_popup = Colour(entry_id="raid_results_gold_popup", shared_id=notable)
raid_retreat_button_unselectable = Colour(entry_id="raid_retreat_button_unselectable", darkness=0.4, saturation=0.2)
raid_retreat_tooltip = Colour(entry_id="raid_retreat_tooltip", shared_id=neutral)
trap_announcement = Colour(entry_id="trap_announcement", shared_id=harmful)
disarm_announcement = Colour(entry_id="disarm_announcement", shared_id=notable)
scouting_text = Colour(entry_id="scouting_text", shared_id=notable)
confirm_dialog_question = Colour(entry_id="confirm_dialog_question", shared_id=neutral)
confirm_dialog_answer = Colour(entry_id="confirm_dialog_answer", shared_id=neutral)
tray_health_bar_background_bottom = Colour(entry_id="tray_health_bar_background_bottom", rgba=(45, 45, 45, 255))
tray_health_bar_background_top = Colour(entry_id="tray_health_bar_background_top", rgba=(18, 18, 18, 255))
tray_health_bar_default_damage_bottom = Colour(entry_id="tray_health_bar_default_damage_bottom", rgba="#a32a00")
tray_health_bar_default_damage_top = Colour(entry_id="tray_health_bar_default_damage_top", rgba="#ffa500")
tray_health_bar_default_heal_bottom = Colour(entry_id="tray_health_bar_default_heal_bottom", rgba="#004e21")
tray_health_bar_default_heal_top = Colour(entry_id="tray_health_bar_default_heal_top", rgba="#00e500")
tray_health_bar_default_current_bottom = Colour(entry_id="tray_health_bar_default_current_bottom", rgba="#150000")
tray_health_bar_default_current_top = Colour(entry_id="tray_health_bar_default_current_top", rgba="#cd0000")
tray_health_bar_corpse_damage_bottom = Colour(entry_id="tray_health_bar_corpse_damage_bottom", rgba="#808080")
tray_health_bar_corpse_damage_top = Colour(entry_id="tray_health_bar_corpse_damage_top", rgba="#F0F0F0")
tray_health_bar_corpse_heal_bottom = Colour(entry_id="tray_health_bar_corpse_heal_bottom", rgba="#808080")
tray_health_bar_corpse_heal_top = Colour(entry_id="tray_health_bar_corpse_heal_top", rgba="#F0F0F0")
tray_health_bar_corpse_current_bottom = Colour(entry_id="tray_health_bar_corpse_current_bottom", rgba="#202020")
tray_health_bar_corpse_current_top = Colour(entry_id="tray_health_bar_corpse_current_top", rgba="#606060")
tray_status_bar_tooltip_health = Colour(entry_id="tray_status_bar_tooltip_health", shared_id=harmful)
tray_status_bar_tooltip_stress = Colour(entry_id="tray_status_bar_tooltip_stress", shared_id=neutral)
tray_status_bar_tooltip_turns_remaining = Colour(entry_id="tray_status_bar_tooltip_turns_remaining", shared_id=neutral)
tray_icon_tooltip_positive = Colour(entry_id="tray_icon_tooltip_positive", shared_id=notable)
tray_icon_tooltip_negative = Colour(entry_id="tray_icon_tooltip_negative", shared_id=harmful)
pop_text_stress_reduce = Colour(entry_id="pop_text_stress_reduce", rgba="#fdf8c7")
pop_text_outline_stress_reduce = Colour(entry_id="pop_text_outline_stress_reduce", rgba="#7c663f")
pop_text_stress_damage = Colour(entry_id="pop_text_stress_damage", rgba="#000000")
pop_text_outline_stress_damage = Colour(entry_id="pop_text_outline_stress_damage", rgba="#c2c2c2")
pop_text_miss = Colour(entry_id="pop_text_miss", rgba="#000000")
pop_text_outline_miss = Colour(entry_id="pop_text_outline_miss", rgba="#9a988f")
pop_text_no_damage = Colour(entry_id="pop_text_no_damage", rgba="#920400")
pop_text_outline_no_damage = Colour(entry_id="pop_text_outline_no_damage", rgba="#1e0400")
pop_text_crit_damage = Colour(entry_id="pop_text_crit_damage", rgba="#ff7100")
pop_text_outline_crit_damage = Colour(entry_id="pop_text_outline_crit_damage", rgba="#480800")
pop_text_damage = Colour(entry_id="pop_text_damage", rgba="#e30900")
pop_text_outline_damage = Colour(entry_id="pop_text_outline_damage", rgba="#390000")
pop_text_deathblow = Colour(entry_id="pop_text_deathblow", rgba="#ff7100")
pop_text_outline_deathblow = Colour(entry_id="pop_text_outline_deathblow", rgba="#480800")
pop_text_death_avoided = Colour(entry_id="pop_text_death_avoided", rgba="#920400")
pop_text_outline_death_avoided = Colour(entry_id="pop_text_outline_death_avoided", rgba="#1e0400")
pop_text_resist = Colour(entry_id="pop_text_resist", rgba="#000000")
pop_text_outline_resist = Colour(entry_id="pop_text_outline_resist", rgba="#9a988f")
pop_text_disease_resist = Colour(entry_id="pop_text_disease_resist", rgba="#000000")
pop_text_outline_disease_resist = Colour(entry_id="pop_text_outline_disease_resist", rgba=(173, 201, 98, 255))
pop_text_pass = Colour(entry_id="pop_text_pass", rgba="#000000")
pop_text_outline_pass = Colour(entry_id="pop_text_outline_pass", rgba="#9a988f")
pop_text_hero_heal = Colour(entry_id="pop_text_hero_heal", rgba="#4fcb4f")
pop_text_outline_hero_heal = Colour(entry_id="pop_text_outline_hero_heal", rgba="#2a4416")
pop_text_hero_heal_crit = Colour(entry_id="pop_text_hero_heal_crit", rgba="#54ff70")
pop_text_outline_hero_heal_crit = Colour(entry_id="pop_text_outline_hero_heal_crit", rgba="#05644f")
pop_text_monster_heal = Colour(entry_id="pop_text_monster_heal", rgba="#4fcb4f")
pop_text_outline_monster_heal = Colour(entry_id="pop_text_outline_monster_heal", rgba="#2a4416")
pop_text_monster_heal_crit = Colour(entry_id="pop_text_monster_heal_crit", rgba="#54ff70")
pop_text_outline_monster_heal_crit = Colour(entry_id="pop_text_outline_monster_heal_crit", rgba="#05644f")
pop_text_buff = Colour(entry_id="pop_text_buff", rgba="#79f8ff")
pop_text_outline_buff = Colour(entry_id="pop_text_outline_buff", rgba="#127298")
pop_text_debuff = Colour(entry_id="pop_text_debuff", rgba="#e26826")
pop_text_outline_debuff = Colour(entry_id="pop_text_outline_debuff", rgba="#7f290b")
pop_text_stun = Colour(entry_id="pop_text_stun", rgba="#f0cf5a")
pop_text_outline_stun = Colour(entry_id="pop_text_outline_stun", rgba="#8e5b11")
pop_text_stun_clear = Colour(entry_id="pop_text_stun_clear", rgba="#f0cf5a")
pop_text_outline_stun_clear = Colour(entry_id="pop_text_outline_stun_clear", rgba="#8e5b11")
pop_text_poison = Colour(entry_id="pop_text_poison", rgba="#c6ff57")
pop_text_outline_poison = Colour(entry_id="pop_text_outline_poison", rgba="#545828")
pop_text_bleed = Colour(entry_id="pop_text_bleed", rgba="#e30900")
pop_text_outline_bleed = Colour(entry_id="pop_text_outline_bleed", rgba="#390000")
pop_text_cured = Colour(entry_id="pop_text_cured", rgba="#fdf8c7")
pop_text_outline_cured = Colour(entry_id="pop_text_outline_cured", rgba="#7c663f")
pop_text_cure_failed = Colour(entry_id="pop_text_cure_failed", rgba="#e26826")
pop_text_outline_cure_failed = Colour(entry_id="pop_text_outline_cure_failed", rgba="#7f290b")
pop_text_tagged = Colour(entry_id="pop_text_tagged", rgba="#e30900")
pop_text_outline_tagged = Colour(entry_id="pop_text_outline_tagged", rgba="#390000")
pop_text_riposte = Colour(entry_id="pop_text_riposte", rgba="#e30900")
pop_text_outline_riposte = Colour(entry_id="pop_text_outline_riposte", rgba="#390000")
pop_text_guard = Colour(entry_id="pop_text_guard", rgba="#79f8ff")
pop_text_outline_guard = Colour(entry_id="pop_text_outline_guard", rgba="#127298")
pop_text_guard_failed = Colour(entry_id="pop_text_guard_failed", rgba="#e26826")
pop_text_outline_guard_failed = Colour(entry_id="pop_text_outline_guard_failed", rgba="#7f290b")
pop_text_full = Colour(entry_id="pop_text_full", rgba="#000000")
pop_text_outline_full = Colour(entry_id="pop_text_outline_full", rgba="#9a988f")
pop_text_heart_attack = Colour(entry_id="pop_text_heart_attack", rgba="#000000")
pop_text_outline_heart_attack = Colour(entry_id="pop_text_outline_heart_attack", rgba="#ffffff")
pop_text_move_resist = Colour(entry_id="pop_text_move_resist", rgba="#000000")
pop_text_outline_move_resist = Colour(entry_id="pop_text_outline_move_resist", rgba="#79f8ff")
pop_text_debuff_resist = Colour(entry_id="pop_text_debuff_resist", rgba="#000000")
pop_text_outline_debuff_resist = Colour(entry_id="pop_text_outline_debuff_resist", rgba="#e26826")
pop_text_stun_resist = Colour(entry_id="pop_text_stun_resist", rgba="#000000")
pop_text_outline_stun_resist = Colour(entry_id="pop_text_outline_stun_resist", rgba="#f0cf5a")
pop_text_poison_resist = Colour(entry_id="pop_text_poison_resist", rgba="#000000")
pop_text_outline_poison_resist = Colour(entry_id="pop_text_outline_poison_resist", rgba="#c6ff57")
pop_text_bleed_resist = Colour(entry_id="pop_text_bleed_resist", rgba="#000000")
pop_text_outline_bleed_resist = Colour(entry_id="pop_text_outline_bleed_resist", rgba="#e30900")
pop_text_heal_failed = Colour(entry_id="pop_text_heal_failed", rgba="#000000")
pop_text_outline_heal_failed = Colour(entry_id="pop_text_outline_heal_failed", rgba="#4fcb4f")
pop_text_stress_dot = Colour(entry_id="pop_text_stress_dot", rgba="#000000")
pop_text_outline_stress_dot = Colour(entry_id="pop_text_outline_stress_dot", rgba="#c2c2c2")
pop_text_stress_dot_resist = Colour(entry_id="pop_text_stress_dot_resist", rgba="#000000")
pop_text_outline_stress_dot_resist = Colour(entry_id="pop_text_outline_stress_dot_resist", rgba="#c2c2c2")
pop_text_control_resist = Colour(entry_id="pop_text_control_resist", rgba="#000000")
pop_text_outline_control_resist = Colour(entry_id="pop_text_outline_control_resist", rgba="#9a988f")
pop_text_hp_heal_dot_onset = Colour(entry_id="pop_text_hp_heal_dot_onset", rgba="#4fcb4f")
pop_text_outline_hp_heal_dot_onset = Colour(entry_id="pop_text_outline_hp_heal_dot_onset", rgba="#2a4416")
pop_text_hp_heal_dot = Colour(entry_id="pop_text_hp_heal_dot", rgba="#4fcb4f")
pop_text_outline_hp_heal_dot = Colour(entry_id="pop_text_outline_hp_heal_dot", rgba="#2a4416")
pop_text_hp_heal_dot_crit = Colour(entry_id="pop_text_hp_heal_dot_crit", rgba="#54ff70")
pop_text_outline_hp_heal_dot_crit = Colour(entry_id="pop_text_outline_hp_heal_dot_crit", rgba="#05644f")
quirk_positive = Colour(entry_id="quirk_positive", shared_id=notable)
quirk_negative = Colour(entry_id="quirk_negative", shared_id=harmful)
quirk_singleton_positive = Colour(entry_id="quirk_singleton_positive", shared_id=notable)
quirk_singleton_negative = Colour(entry_id="quirk_singleton_negative", shared_id=harmful)
quirk_new_pulse_to = Colour(entry_id="quirk_new_pulse_to", shared_id=neutral)
quirk_tooltip_description = Colour(entry_id="quirk_tooltip_description", shared_id=neutral)
equipment_level = Colour(entry_id="equipment_level", shared_id=neutral)
equipment_tooltip_title = Colour(entry_id="equipment_tooltip_title", shared_id=notable)
equipment_tooltip_body = Colour(entry_id="equipment_tooltip_body", shared_id=neutral)
resistance_name = Colour(entry_id="resistance_name", shared_id=neutral)
resistance_value = Colour(entry_id="resistance_value", shared_id=neutral)
campaign_status_affliction = Colour(entry_id="campaign_status_affliction", shared_id=neutral)
raid_quest_info_complete = Colour(entry_id="raid_quest_info_complete", shared_id=notable)
raid_quest_info_name = Colour(entry_id="raid_quest_info_name", shared_id=notable)
raid_quest_info_goals = Colour(entry_id="raid_quest_info_goals", shared_id=neutral)
town_quest_difficulty_1 = Colour
town_quest_difficulty_3 = Colour(entry_id="town_quest_difficulty_3", rgba=(233, 170, 98, 255))
town_quest_difficulty_5 = Colour(entry_id="town_quest_difficulty_5", rgba=(255, 87, 49, 255))
town_quest_difficulty_6 = Colour(entry_id="town_quest_difficulty_6", shared_id=harmful)
trinket_hero_class_requirement = Colour(entry_id="trinket_hero_class_requirement", shared_id=notable)
realm_inventory_trinket_sell_description = Colour(entry_id="realm_inventory_trinket_sell_description",
                                                  shared_id=notable)
realm_inventory_trinket_sell_instruction = Colour(entry_id="realm_inventory_trinket_sell_instruction",
                                                  shared_id=neutral)
provision_sell_back_info = Colour(entry_id="provision_sell_back_info", rgba="#5d5a50")
provision_quest_info_dungeon_name = Colour(entry_id="provision_quest_info_dungeon_name", shared_id=notable)
provision_quest_info_specs = Colour(entry_id="provision_quest_info_specs", shared_id=neutral)
raid_loading_screen_title = Colour(entry_id="raid_loading_screen_title", shared_id=notable)
raid_loading_screen_tip = Colour(entry_id="raid_loading_screen_tip", shared_id=neutral)
town_screen_building_name = Colour(entry_id="town_screen_building_name", shared_id=notable)
town_screen_building_description = Colour(entry_id="town_screen_building_description", shared_id=neutral)
town_screen_colour_grade1 = Colour(entry_id="town_screen_colour_grade1", rgba=(255, 255, 255, 255))
town_screen_colour_grade2 = Colour(entry_id="town_screen_colour_grade2", rgba=(255, 255, 255, 255))
town_screen_colour_grade3 = Colour(entry_id="town_screen_colour_grade3", rgba=(255, 255, 255, 255))
town_screen_colour_grade4 = Colour(entry_id="town_screen_colour_grade4", rgba=(255, 255, 255, 255))
hero_slot_name = Colour(entry_id="hero_slot_name", shared_id=notable)
quest_select_progress_xpbar_tooltip = Colour(entry_id="quest_select_progress_xpbar_tooltip", shared_id=neutral)
quest_select_progress_town_event_icon_tooltip = Colour(entry_id="quest_select_progress_town_event_icon_tooltip",
                                                       shared_id=neutral)
town_graveyard_story = Colour(entry_id="town_graveyard_story", shared_id=neutral)
town_graveyard_hero_name = Colour(entry_id="town_graveyard_hero_name", shared_id=notable)
town_graveyard_hero_death_week = Colour(entry_id="town_graveyard_hero_death_week", rgba=(80, 79, 75, 255))
town_graveyard_death_count = Colour(entry_id="town_graveyard_death_count", rgba=(134, 9, 2, 255))
town_activity_log_week_count = Colour(entry_id="town_activity_log_week_count", shared_id=neutral)
town_statue_story = Colour(entry_id="town_statue_story", shared_id=neutral)
kickstarter = Colour(entry_id="kickstarter", rgba=(77, 191, 122, 255))
trophy = Colour(entry_id="trophy", rgba=(222, 182, 105, 255))
ancestral = Colour(entry_id="ancestral", rgba=(224, 39, 0, 255))
darkest_dungeon = Colour(entry_id="darkest_dungeon", rgba=(224, 39, 0, 255))
ancestral_shambler = Colour(entry_id="ancestral_shambler", rgba=(224, 39, 0, 255))
madman = Colour(entry_id="madman", rgba=(224, 39, 0, 255))
courtier = Colour(entry_id="courtier", rgba=(194, 69, 0, 255))
collector = Colour(entry_id="collector", rgba=(241, 107, 4, 255))
uncommon = Colour(entry_id="uncommon", rgba=(96, 149, 75, 255))
common = Colour(entry_id="common", rgba=(168, 168, 168, 255))
very_common = Colour(entry_id="very_common", rgba=(168, 168, 168, 255))
rare = Colour(entry_id="rare", rgba=(59, 97, 167, 255))
very_rare = Colour(entry_id="very_rare", rgba=(194, 69, 0, 255))
crow = Colour(entry_id="crow", rgba=(224, 39, 0, 255))
roster_full = Colour(entry_id="roster_full", shared_id=notable)
front_end_start_screen = Colour(entry_id="front_end_start_screen", shared_id=notable)
front_end_build_number = Colour(entry_id="front_end_build_number", rgba=(80, 80, 80, 255))
front_end_save_slot = Colour(entry_id="front_end_save_slot", shared_id=notable)
front_end_save_slot_inactive = Colour(entry_id="front_end_save_slot_inactive", rgba=(73, 71, 68, 255))
front_end_save_area = Colour(entry_id="front_end_save_area", shared_id=neutral)
front_end_ticker = Colour(entry_id="front_end_ticker", rgba=(73, 71, 68, 255))
front_end_preamble = Colour(entry_id="front_end_preamble", shared_id=neutral)
front_end_campaign = Colour(entry_id="front_end_campaign", shared_id=notable)
front_end_controls_element_text = Colour(entry_id="front_end_controls_element_text", shared_id=neutral)
loading_screen_continue = Colour(entry_id="loading_screen_continue", shared_id=neutral)
loading_screen_continue_pulse_to = Colour(entry_id="loading_screen_continue_pulse_to", rgba=(200, 180, 110, 0))
tutorial_popup_title = Colour(entry_id="tutorial_popup_title", shared_id=notable)
tutorial_popup_description = Colour(entry_id="tutorial_popup_description", shared_id=neutral)
mailing_list_title = Colour(entry_id="mailing_list_title", shared_id=notable)
mailing_list_description = Colour(entry_id="mailing_list_description", shared_id=neutral)
mailing_list_answer = Colour(entry_id="mailing_list_answer", shared_id=neutral)
journal_popup_title = Colour(entry_id="journal_popup_title", shared_id=notable)
journal_popup_text = Colour(entry_id="journal_popup_text", rgba=(21, 14, 5, 255))
journal_popup_count = Colour(entry_id="journal_popup_count", rgba=(21, 14, 5, 255))
menu_base_element_text_base = Colour(entry_id="menu_base_element_text_base", shared_id=neutral)
menu_base_element_text_highlight = Colour(entry_id="menu_base_element_text_highlight", shared_id=notable)
menu_controls_category = Colour(entry_id="menu_controls_category", shared_id=notable)
menu_controls_element = Colour(entry_id="menu_controls_element", shared_id=neutral)
menu_options_element_name = Colour(entry_id="menu_options_element_name", shared_id=neutral)
menu_options_element_name_disabled = Colour(entry_id="menu_options_element_name_disabled", darkness=0.4, saturation=0.0)
menu_options_element_name_tooltip_cant_modify = Colour(entry_id="menu_options_element_name_tooltip_cant_modify",
                                                       shared_id=harmful)
menu_options_element_name_tooltip = Colour(entry_id="menu_options_element_name_tooltip", shared_id=neutral)
menu_options_element_control = Colour(entry_id="menu_options_element_control", shared_id=neutral)
menu_options_element_control_disabled = Colour(entry_id="menu_options_element_control_disabled", darkness=0.4,
                                               saturation=0.0)
menu_options_element_control_button = Colour(entry_id="menu_options_element_control_button", rgba="#fff",
                                             saturation=1.0)
menu_options_element_control_button_disabled = Colour(entry_id="menu_options_element_control_button_disabled",
                                                      darkness=0.4,
                                                      saturation=0.0)
menu_options_require_restart = Colour(entry_id="menu_options_require_restart", shared_id=harmful)
equipment_level_0 = Colour(entry_id="equipment_level_0", rgba=(215, 213, 205, 255))
equipment_level_1 = Colour(entry_id="equipment_level_1", rgba=(215, 213, 205, 255))
equipment_level_2 = Colour(entry_id="equipment_level_2", rgba=(105, 190, 75, 255))
equipment_level_3 = Colour(entry_id="equipment_level_3", rgba=(62, 114, 212, 255))
equipment_level_4 = Colour(entry_id="equipment_level_4", shared_id=harmful)
loot_take_all_tooltip = Colour(entry_id="loot_take_all_tooltip", shared_id=neutral)
loot_take_all_text = Colour(entry_id="loot_take_all_text", shared_id=notable)
loot_close_tooltip = Colour(entry_id="loot_close_tooltip", shared_id=neutral)
loot_close_text = Colour(entry_id="loot_close_text", shared_id=notable)
event_hunger_eat_tooltip = Colour(entry_id="event_hunger_eat_tooltip", shared_id=neutral)
event_hunger_eat_text = Colour(entry_id="event_hunger_eat_text", shared_id=notable)
event_hunger_starve_tooltip = Colour(entry_id="event_hunger_starve_tooltip", shared_id=neutral)
event_hunger_starve_text = Colour(entry_id="event_hunger_starve_text", shared_id=notable)
round_display_number = Colour(entry_id="round_display_number", shared_id=notable)
glossary_quote = Colour(entry_id="glossary_quote", shared_id=notable)
glossary_term = Colour(entry_id="glossary_term", shared_id=notable)
glossary_term_definition = Colour(entry_id="glossary_term_definition", shared_id=neutral)
quest_info_camp_bonus_skill_tooltip = Colour(entry_id="quest_info_camp_bonus_skill_tooltip", shared_id=notable)
quest_info_camp_bonus_skill_stats_tooltip = Colour(entry_id="quest_info_camp_bonus_skill_stats_tooltip",
                                                   shared_id=neutral)
sanitarium_treatment_header = Colour(entry_id="sanitarium_treatment_header", shared_id=notable)
sanitarium_treatment_entry = Colour(entry_id="sanitarium_treatment_entry", shared_id=neutral)
sanitarium_treatment_positive_entry = Colour(entry_id="sanitarium_treatment_positive_entry", shared_id=notable)
sanitarium_treatment_positive_entry_locked = Colour(entry_id="sanitarium_treatment_positive_entry_locked", darkness=0.4,
                                                    saturation=0.2)
sanitarium_treatment_positive_entry_selected = Colour(entry_id="sanitarium_treatment_positive_entry_selected",
                                                      shared_id=notable)
sanitarium_treatment_max_locked = Colour(entry_id="sanitarium_treatment_max_locked", darkness=0.4, saturation=0.2)
sanitarium_treatment_negative_entry = Colour(entry_id="sanitarium_treatment_negative_entry", shared_id=harmful)
sanitarium_treatment_negative_entry_locked = Colour(entry_id="sanitarium_treatment_negative_entry_locked",
                                                    shared_id=harmful)
sanitarium_treatment_negative_entry_selected = Colour(entry_id="sanitarium_treatment_negative_entry_selected",
                                                      shared_id=harmful)
sanitarium_treatment_disease_entry = Colour(entry_id="sanitarium_treatment_disease_entry", rgba=(121, 141, 69, 255))
sanitarium_treatment_disease_entry_locked = Colour(entry_id="sanitarium_treatment_disease_entry_locked",
                                                   shared_id=harmful)
sanitarium_treatment_disease_entry_selected = Colour(entry_id="sanitarium_treatment_disease_entry_selected",
                                                     rgba=(173, 201, 98, 255))
monster_panel_monster_name = Colour(entry_id="monster_panel_monster_name", shared_id=harmful)
monster_panel_monster_type = Colour(entry_id="monster_panel_monster_type", shared_id=neutral)
monster_panel_monster_stats = Colour(entry_id="monster_panel_monster_stats", shared_id=neutral)
monster_panel_hero_attack_stats = Colour(entry_id="monster_panel_hero_attack_stats", shared_id=notable)
monster_panel_resistances_title = Colour(entry_id="monster_panel_resistances_title", rgba="#5d5a50")
monster_panel_resistances_entry = Colour(entry_id="monster_panel_resistances_entry", shared_id=neutral)
monster_panel_skills_title = Colour(entry_id="monster_panel_skills_title", rgba="#5d5a50")
monster_panel_skills_entry = Colour(entry_id="monster_panel_skills_entry", shared_id=neutral)
monster_panel_hp = Colour(entry_id="monster_panel_hp", shared_id=harmful)
quest_complete_tooltip = Colour(entry_id="quest_complete_tooltip", shared_id=neutral)
quest_complete_text = Colour(entry_id="quest_complete_text", shared_id=notable)
realm_inventory_add_trinket_dialog_heading = Colour(entry_id="realm_inventory_add_trinket_dialog_heading",
                                                    shared_id=neutral)
realm_inventory_add_trinket_dialog_edit_box = Colour(entry_id="realm_inventory_add_trinket_dialog_edit_box",
                                                     shared_id=neutral)
stagecoach_add_hero_dialog_heading = Colour(entry_id="stagecoach_add_hero_dialog_heading", shared_id=neutral)
stagecoach_add_hero_dialog_edit_box = Colour(entry_id="stagecoach_add_hero_dialog_edit_box", shared_id=neutral)
stagecoach_empty_info_text = Colour(entry_id="stagecoach_empty_info_text", shared_id=neutral)
stagecoach_prisoner_rescued = Colour(entry_id="stagecoach_prisoner_rescued", shared_id=notable)
hero_slot_dimmed = Colour(entry_id="hero_slot_dimmed", shared_id=town_roster_portrait_unselectable)
credits_category = Colour(entry_id="credits_category", shared_id=notable)
credits_entry = Colour(entry_id="credits_entry", shared_id=neutral)
credits_level_0 = Colour(entry_id="credits_level_0", shared_id=notable)
credits_level_1 = Colour(entry_id="credits_level_1", shared_id=notable)
credits_level_2 = Colour(entry_id="credits_level_2", shared_id=neutral)
subtitle_context_raid = Colour(entry_id="subtitle_context_raid", shared_id=notable)
subtitle_context_front_end = Colour(entry_id="subtitle_context_front_end", shared_id=notable)
subtitle_context_loading_screen = Colour(entry_id="subtitle_context_loading_screen", shared_id=notable)
subtitle_context_town = Colour(entry_id="subtitle_context_town", shared_id=notable)
subtitle_context_movie = Colour(entry_id="subtitle_context_movie", shared_id=notable)
subtitle_context_raid_results = Colour(entry_id="subtitle_context_raid_results", shared_id=notable)
game_over_estate_name = Colour(entry_id="game_over_estate_name", shared_id=notable)
game_over_estate_number_of_weeks = Colour(entry_id="game_over_estate_number_of_weeks", shared_id=neutral)
game_over_estate_number_of_dead_heroes = Colour(entry_id="game_over_estate_number_of_dead_heroes", shared_id=neutral)
game_over_estate_reason = Colour(entry_id="game_over_estate_reason", shared_id=harmful)
town_event_story_title_bad = Colour(entry_id="town_event_story_title_bad", shared_id=notable)
town_event_story_title_good = Colour(entry_id="town_event_story_title_good", shared_id=notable)
town_event_story_title_neutral = Colour(entry_id="town_event_story_title_neutral", shared_id=notable)
town_event_story_description = Colour(entry_id="town_event_story_description", rgba=(21, 14, 5, 255))
town_event_info = Colour(entry_id="town_event_info", shared_id=notable)
town_heirloom_exchange_title = Colour(entry_id="town_heirloom_exchange_title", shared_id=notable)
town_heirloom_exchange_from_amount = Colour(entry_id="town_heirloom_exchange_from_amount", shared_id=neutral)
town_heirloom_exchange_to_amount = Colour(entry_id="town_heirloom_exchange_to_amount", shared_id=notable)
demo_message = Colour(entry_id="demo_message", shared_id=notable)
help_panel_controls = Colour(entry_id="help_panel_controls", shared_id=notable)
controls_panel_text = Colour(entry_id="controls_panel_text", shared_id=notable)
controls_panel_title = Colour(entry_id="controls_panel_title", shared_id=notable)
controls_panel_context_title = Colour(entry_id="controls_panel_context_title", shared_id=notable)
controls_panel_button_description = Colour(entry_id="controls_panel_button_description", shared_id=neutral)
controls_panel_context_title_text = Colour(entry_id="controls_panel_context_title_text", shared_id=notable)
map_input_preview_pan = Colour(entry_id="map_input_preview_pan", shared_id=neutral)
map_input_preview_zoom_in = Colour(entry_id="map_input_preview_zoom_in", shared_id=neutral)
map_input_preview_zoom_out = Colour(entry_id="map_input_preview_zoom_out", shared_id=neutral)
map_input_preview_reset = Colour(entry_id="map_input_preview_reset", shared_id=neutral)
input_command_input_preview_text_default = Colour(entry_id="input_command_input_preview_text_default",
                                                  shared_id=neutral)
input_command_input_preview_saturation_fade_base = Colour(entry_id="input_command_input_preview_saturation_fade_base",
                                                          rgba=(100, 100, 100, 255), saturation=0.0)
primary1 = Colour(entry_id="primary1", rgba="#175190")
primary2 = Colour(entry_id="primary2", rgba="#c82929")
secondary1 = Colour(entry_id="secondary1", rgba="#9f43a1")
secondary2 = Colour(entry_id="secondary2", rgba="#3bb265")
start1 = Colour(entry_id="start1", shared_id=neutral)
start2 = Colour(entry_id="start2", shared_id=neutral)
shoulder_l = Colour(entry_id="shoulder_l", shared_id=neutral)
shoulder_r = Colour(entry_id="shoulder_r", shared_id=neutral)
stick_l = Colour(entry_id="stick_l", shared_id=neutral)
stick_r = Colour(entry_id="stick_r", shared_id=neutral)
dpad_l = Colour(entry_id="dpad_l", shared_id=neutral)
dpad_r = Colour(entry_id="dpad_r", shared_id=neutral)
dpad_u = Colour(entry_id="dpad_u", shared_id=neutral)
dpad_d = Colour(entry_id="dpad_d", shared_id=neutral)
tpad_l = Colour(entry_id="tpad_l", shared_id=neutral)
tpad_r = Colour(entry_id="tpad_r", shared_id=neutral)
tpad = Colour(entry_id="tpad", shared_id=neutral)
game_mode_select_dialog_question = Colour(entry_id="game_mode_select_dialog_question", shared_id=notable)
game_mode_select_dialog_answers = Colour(entry_id="game_mode_select_dialog_answers", shared_id=neutral)
game_mode_select_dialog_tooltip = Colour(entry_id="game_mode_select_dialog_tooltip", shared_id=neutral)
save_slot_ugc_banner_text = Colour(entry_id="save_slot_ugc_banner_text", shared_id=neutral)
user_generated_content_title_text = Colour(entry_id="user_generated_content_title_text", shared_id=notable)
user_generated_content_sub_title_text = Colour(entry_id="user_generated_content_sub_title_text", shared_id=neutral)
user_generated_content_entry_text = Colour(entry_id="user_generated_content_entry_text", shared_id=notable)
user_generated_content_entry_tooltip = Colour(entry_id="user_generated_content_entry_tooltip", shared_id=neutral)
user_generated_content_entry_tooltip_build = Colour(entry_id="user_generated_content_entry_tooltip_build", darkness=0.4,
                                                    saturation=0.0)
town_district_entry_title_not_built = Colour(entry_id="town_district_entry_title_not_built", shared_id=neutral)
town_district_entry_details_not_built = Colour(entry_id="town_district_entry_details_not_built", darkness=0.4,
                                               saturation=0.0)
town_district_entry_title_built = Colour(entry_id="town_district_entry_title_built", shared_id=notable)
town_district_entry_title_unavailable = Colour(entry_id="town_district_entry_title_unavailable", darkness=0.4,
                                               saturation=0.0)
town_district_entry_details_built = Colour(entry_id="town_district_entry_details_built", shared_id=neutral)
town_district_entry_details_unavailable = Colour(entry_id="town_district_entry_details_unavailable", darkness=0.4,
                                                 saturation=0.0)
town_district_blueprint_tally = Colour(entry_id="town_district_blueprint_tally", shared_id=notable)
town_district_cost_numbers = Colour(entry_id="town_district_cost_numbers", shared_id=notable)
town_district_cost_numbers_insufficient = Colour(entry_id="town_district_cost_numbers_insufficient", shared_id=harmful)
town_district_checkbox_disabled = Colour(entry_id="town_district_checkbox_disabled", darkness=0.4, saturation=0.0)
town_district_tooltip = Colour(entry_id="town_district_tooltip", shared_id=neutral)
save_slot_dlc_banner_text = Colour(entry_id="save_slot_dlc_banner_text", rgba="#93844e")
save_slot_dlc_disabled_banner_text = Colour(entry_id="save_slot_dlc_disabled_banner_text", shared_id=neutral)
downloadable_content_title_text = Colour(entry_id="downloadable_content_title_text", shared_id=notable)
downloadable_content_sub_title_text = Colour(entry_id="downloadable_content_sub_title_text", shared_id=neutral)
downloadable_content_entry_text = Colour(entry_id="downloadable_content_entry_text", darkness=0.4, saturation=0.0)
downloadable_content_entry_tooltip = Colour(entry_id="downloadable_content_entry_tooltip", shared_id=neutral)
downloadable_content_entry_tooltip_build = Colour(entry_id="downloadable_content_entry_tooltip_build", darkness=0.5,
                                                  saturation=0.0)
downloadable_content_permanently_enabled_text = Colour(entry_id="downloadable_content_permanently_enabled_text",
                                                       shared_id=notable)
downloadable_content_permanently_enabled_checkbox = Colour(entry_id="downloadable_content_permanently_enabled_checkbox",
                                                           darkness=0.4, saturation=0.0)
downloadable_content_permanently_enabled_icon = Colour(entry_id="downloadable_content_permanently_enabled_icon",
                                                       shared_id=white)
set_description_inactive = Colour(entry_id="set_description_inactive", rgba="#555555")
set_description_active = Colour(entry_id="set_description_active", rgba="#00ff00")
set_title = Colour(entry_id="set_title", rgba="#84182d")
# town_event_tooltip = Colour(entry_id="town_event_tooltip", shared_id=neutral)
singleton_quirk_tooltip_description = Colour(entry_id="singleton_quirk_tooltip_description", shared_id=notable)
skip_curio_text = Colour(entry_id="skip_curio_text", shared_id=notable)
wave_countdown_overlay_bar_bg_top = Colour(entry_id="wave_countdown_overlay_bar_bg_top", rgba="#111111")
wave_countdown_overlay_bar_bg_bottom = Colour(entry_id="wave_countdown_overlay_bar_bg_bottom", rgba="#333333")
wave_countdown_overlay_bar_top_left = Colour(entry_id="wave_countdown_overlay_bar_top_left", rgba="#00d7a2")
wave_countdown_overlay_bar_top_right = Colour(entry_id="wave_countdown_overlay_bar_top_right", rgba="#00d7a2")
wave_countdown_overlay_bar_bottom_left = Colour(entry_id="wave_countdown_overlay_bar_bottom_left", rgba="#002438")
wave_countdown_overlay_bar_bottom_right = Colour(entry_id="wave_countdown_overlay_bar_bottom_right", rgba="#002438")
wave_countdown_count = Colour(entry_id="wave_countdown_count", rgba="#00d7a2")
wave_kill_count = Colour(entry_id="wave_kill_count", rgba="#00d7a2")
wave_progress_tooltip_reward_tier_small = Colour(entry_id="wave_progress_tooltip_reward_tier_small", shared_id=neutral)
wave_progress_tooltip_reward_tier_medium = Colour(entry_id="wave_progress_tooltip_reward_tier_medium", rgba="#436b6b")
wave_progress_tooltip_reward_tier_large = Colour(entry_id="wave_progress_tooltip_reward_tier_large", rgba="#5fc9af")
wave_progress_tooltip_reward_tier_wonderous = Colour(entry_id="wave_progress_tooltip_reward_tier_wonderous",
                                                     rgba="#f7e56f")
wave_skill_reset_announcement = Colour(entry_id="wave_skill_reset_announcement", rgba="#a3ffee")
pop_text_guard_break = Colour(entry_id="pop_text_guard_break", rgba="#f0cf5a")
pop_text_outline_guard_break = Colour(entry_id="pop_text_outline_guard_break", rgba="#8e5b11")

# com._colours.darkest
comet = Colour(entry_id="comet", rgba="#a3ffee")
kill_counter_display_number = Colour(entry_id="kill_counter_display_number", rgba="#C8B46E")
shard_escrow_number = Colour(entry_id="shard_escrow_number", shared_id=comet)
mildred = Colour(entry_id="mildred", rgba="#a3ffee")
shard_display_number = Colour(entry_id="shard_display_number", rgba="#a3ffee")
raid_results_kill_counter = Colour(entry_id="raid_results_kill_counter", rgba="#ff0000")
raid_results_kill_counter_tampered = Colour(entry_id="raid_results_kill_counter_tampered", rgba="#ff6000")
raid_results_shard_number = Colour(entry_id="raid_results_shard_number", rgba="#a3ffee")
raid_results_shard_inventory_title = Colour(entry_id="raid_results_shard_inventory_title", rgba="#a3ffee")
raid_results_quest_result_endless = Colour(entry_id="raid_results_quest_result_endless", rgba="#a3ffee")
town_quest_select_endless_wave_highscore = Colour(entry_id="town_quest_select_endless_wave_highscore", rgba="#a3ffee")
town_quest_modifier_header = Colour(entry_id="town_quest_modifier_header", shared_id=neutral)
town_quest_modifier_name = Colour(entry_id="town_quest_modifier_name", rgba="#a3ffee")
pop_text_damage_reflect = Colour(entry_id="pop_text_damage_reflect", rgba="#000000")
pop_text_outline_damage_reflect = Colour(entry_id="pop_text_outline_damage_reflect", rgba=(200, 180, 110, 255))
pop_text_refresh_skills = Colour(entry_id="pop_text_refresh_skills", rgba="#79f8ff")
pop_text_outline_refresh_skills = Colour(entry_id="pop_text_outline_refresh_skills", rgba="#127298")
corpse_crystal_spawn_announcement = Colour(entry_id="corpse_crystal_spawn_announcement", rgba="#a3ffee")
wave_log_kill_count = Colour(entry_id="wave_log_kill_count", rgba="#a3ffee")
endless_highscore_title = Colour(entry_id="endless_highscore_title", rgba="#49d5cd")
endless_highscore_killcount = Colour(entry_id="endless_highscore_killcount", shared_id=comet)
endless_highscore_killcount_text = Colour(entry_id="endless_highscore_killcount_text", shared_id=comet)
endless_highscore_killcount_tampered_text = Colour(entry_id="endless_highscore_killcount_tampered_text", rgba="#ff6000")
endless_highscore_killcount_text_outline = Colour(entry_id="endless_highscore_killcount_text_outline", rgba="#000000")
town_event_tooltip = Colour(entry_id="town_event_tooltip", shared_id=neutral)
thing = Colour(entry_id="thing", rgba="#4a929c")
memory = Colour(entry_id="memory", shared_id=notable)

# crimson_court._colours.darkest
pop_text_vampire = Colour(entry_id="pop_text_vampire", rgba="#000000")
pop_text_outline_vampire = Colour(entry_id="pop_text_outline_vampire", rgba="#f40006")
pop_text_vampire_resist = Colour(entry_id="pop_text_vampire_resist", rgba="#000000")
pop_text_outline_vampire_resist = Colour(entry_id="pop_text_outline_vampire_resist", rgba="#9a988f")
pop_text_shuffle_dot = Colour(entry_id="pop_text_shuffle_dot", rgba="#000000")
pop_text_outline_shuffle_dot = Colour(entry_id="pop_text_outline_shuffle_dot", rgba="#79f8ff")
pop_text_shuffle_dot_resist = Colour(entry_id="pop_text_shuffle_dot_resist", rgba="#000000")
pop_text_outline_shuffle_dot_resist = Colour(entry_id="pop_text_outline_shuffle_dot_resist", rgba="#79f8ff")
pop_text_actor_dot_complete = Colour(entry_id="pop_text_actor_dot_complete", rgba="#000000")
pop_text_outline_actor_dot_complete = Colour(entry_id="pop_text_outline_actor_dot_complete", rgba="#fd0006")
quest_select_infestation_tooltip_verbose = Colour(entry_id="quest_select_infestation_tooltip_verbose",
                                                  shared_id=neutral)
quest_select_infestation_tooltip_description = Colour(entry_id="quest_select_infestation_tooltip_description",
                                                      rgba=(177, 25, 0, 255))
quest_select_dungeon_estate_inventory_dependency_count_unmet = Colour(
    entry_id="quest_select_dungeon_estate_inventory_dependency_count_unmet", shared_id=harmful)
quest_select_dungeon_estate_inventory_dependency_count_met = Colour(
    entry_id="quest_select_dungeon_estate_inventory_dependency_count_met", shared_id=notable)
provision_infestation_quirk_evolution_death_hero_type = Colour(
    entry_id="provision_infestation_quirk_evolution_death_hero_type", shared_id=neutral)
provision_infestation_quirk_evolution_death_hero_count = Colour(
    entry_id="provision_infestation_quirk_evolution_death_hero_count", shared_id=harmful)
provision_infestation_quirk_evolution_death_hero_description = Colour(
    entry_id="provision_infestation_quirk_evolution_death_hero_description", shared_id=neutral)
town_activity_building_contagion_description = Colour(entry_id="town_activity_building_contagion_description",
                                                      shared_id=neutral)
town_activity_building_contagion_none = Colour(entry_id="town_activity_building_contagion_none", shared_id=neutral)
town_activity_building_contagion_low = Colour(entry_id="town_activity_building_contagion_low", rgba="#d9ab1d")
town_activity_building_contagion_medium = Colour(entry_id="town_activity_building_contagion_medium", rgba="#e25500")
town_activity_building_contagion_high = Colour(entry_id="town_activity_building_contagion_high", shared_id=harmful)
quirk_vampire = Colour(entry_id="quirk_vampire", rgba="#f40006")
# crimson_court = Colour(entry_id="crimson_court", shared_id=harmful)
blueprint = Colour(entry_id="blueprint", shared_id=notable)

# shieldbreaker._colours.darkest
pop_text_health_damage_block_onset = Colour(entry_id="pop_text_health_damage_block_onset", rgba="#000000")
pop_text_outline_health_damage_block_onset = Colour(entry_id="pop_text_outline_health_damage_block_onset",
                                                    rgba=(200, 180, 110, 255))
pop_text_health_damage_block = Colour(entry_id="pop_text_health_damage_block", rgba="#000000")
pop_text_outline_health_damage_block = Colour(entry_id="pop_text_outline_health_damage_block",
                                              rgba=(200, 180, 110, 255))
pop_text_tag_block = Colour(entry_id="pop_text_tag_block", rgba="#000000")
pop_text_outline_tag_block = Colour(entry_id="pop_text_outline_tag_block", rgba=(200, 180, 110, 255))
shieldbreaker = Colour(entry_id="shieldbreaker", rgba="#e0ddce")

# arena._colours.darkest
pop_text_daze = Colour(entry_id="pop_text_daze", rgba="#f0cf5a")
pop_text_outline_daze = Colour(entry_id="pop_text_outline_daze", rgba="#8e5b11")
pop_text_daze_resist = Colour(entry_id="pop_text_daze_resist", rgba="#000000")
pop_text_outline_daze_resist = Colour(entry_id="pop_text_outline_daze_resist", rgba="#f0cf5a")
arena = Colour(entry_id="arena", shared_id=harmful)
founder = Colour(entry_id="founder", rgba=(0, 255, 0, 255))
prize_booth_reward_locked_level = Colour(entry_id="prize_booth_reward_locked_level", rgba=(177, 177, 177, 255))
prize_booth_reward_earned_level = Colour(entry_id="prize_booth_reward_earned_level", shared_id=notable)
rankings_current_rank = Colour(entry_id="rankings_current_rank", shared_id=notable)
rankings_next_rank = Colour(entry_id="rankings_next_rank", rgba=(107, 107, 107, 255))
rankings_section_title = Colour(entry_id="rankings_section_title", shared_id=notable)
rankings_stats = Colour(entry_id="rankings_stats", rgba=(107, 107, 107, 255))
rankings_match_history_player = Colour(entry_id="rankings_match_history_player", shared_id=notable)
rankings_match_history_opponent = Colour(entry_id="rankings_match_history_opponent", shared_id=harmful)
rankings_match_history_vs = Colour(entry_id="rankings_match_history_vs", shared_id=harmful)
rankings_leaderboards = Colour(entry_id="rankings_leaderboards", shared_id=notable)
direct_challenge_friend = Colour(entry_id="direct_challenge_friend", rgba=(177, 177, 177, 255))
matchmaking_time = Colour(entry_id="matchmaking_time", rgba=(177, 177, 177, 255))
party_setup_title = Colour(entry_id="party_setup_title", rgba=(177, 177, 177, 255))
party_setup_connection = Colour(entry_id="party_setup_connection", rgba=(177, 177, 177, 255))
party_setup_message = Colour(entry_id="party_setup_message", rgba=(177, 177, 177, 255))
reward_earned = Colour(entry_id="reward_earned", rgba=(77, 191, 122, 255))
reward_locked = Colour(entry_id="reward_locked", rgba=(177, 177, 177, 255))
reward_separator = Colour(entry_id="reward_separator", rgba=(177, 177, 177, 255))
invite_sent = Colour(entry_id="invite_sent", shared_id=notable)
results_desc = Colour(entry_id="results_desc", shared_id=notable)
results_title = Colour(entry_id="results_title", shared_id=harmful)
results_prestige = Colour(entry_id="results_prestige", shared_id=notable)
results_prestige_dead_ally = Colour(entry_id="results_prestige_dead_ally", rgba=(255, 0, 0, 255))
results_prestige_dead_enemy = Colour(entry_id="results_prestige_dead_enemy", shared_id=notable)
results_prestige_inactive = Colour(entry_id="results_prestige_inactive", rgba=(177, 177, 177, 255))
stalemate_lose = Colour(entry_id="stalemate_lose", shared_id=harmful)
stalemate_win = Colour(entry_id="stalemate_win", shared_id=notable)
crimson_court = Colour(entry_id="crimson_court", shared_id=harmful)
# comet = Colour(entry_id="comet", rgba="#a3ffee")
league_novice = Colour(entry_id="league_novice", rgba=(203, 203, 203, 255))
league_apprentice = Colour(entry_id="league_apprentice", rgba=(96, 149, 75, 255))
league_veteran = Colour(entry_id="league_veteran", rgba=(59, 97, 167, 255))
league_champion = Colour(entry_id="league_champion", rgba=(194, 69, 0, 255))
league_darkest = Colour(entry_id="league_darkest", rgba=(224, 39, 0, 255))
rank_display_tier = Colour(entry_id="rank_display_tier", rgba=(203, 203, 203, 255))
party_builder_name_not_set = Colour(entry_id="party_builder_name_not_set", rgba=(87, 87, 87, 255))
party_builder_name_set = Colour(entry_id="party_builder_name_set", shared_id=notable)
party_builder_tooltip_desc = Colour(entry_id="party_builder_tooltip_desc", rgba=(87, 87, 87, 255))
news_popup_title = Colour(entry_id="news_popup_title", shared_id=notable)
news_popup_description = Colour(entry_id="news_popup_description", shared_id=neutral)
