from enum import Enum


class BankDir(Enum):
    AMBIENCE_DUNGEON = "/ambience/dungeon"
    AMBIENCE_DUNGEON_QUEST = "/ambience/dungeon/quest"
    AMBIENCE_LOCAL = "/ambience/local"
    AMBIENCE_TOWN = "/ambience/town"
    CAMP_SKILL = "/camp/skill"
    CHAR_ALLY = "/char/ally"
    CHAR_ENEMY = "/char/enemy"
    CHAR_ENEMY_SHARED = "/char/enemy/_shared"
    GENERAL_CHAR = "/general/char"
    GENERAL_COMBAT = "/general/combat"
    GENERAL_ITEMS = "/general/items"
    GENERAL_MAP = "/general/map"
    GENERAL_PARTY = "/general/party"
    GENERAL_PARTY_FOOT_ASSETS_HEROES = "/general/party/foot_assets_heroes"
    GENERAL_PARTY_FOOT_ASSETS_SURFACES = "/general/party/foot_assets_surfaces"
    GENERAL_RAID_SCREEN = "/general/raid_screen"
    GENERAL_STATUS = "/general/status"
    GENERAL_TITLE_SCREEN = "/general/title_screen"
    MUSIC = "/music"
    MUSIC_ASSETS = "/music/_music_assets"
    PROPS_CURIOS = "/props/curios"
    PROPS_CURIOS_IGNORED = "/props/curios/!!!_IGNORE FOR NOW"
    PROPS_CURIOS_DEFAULTS = "/props/curios/!!_curio_defaults"
    PROPS_CURIOS_DEFAULTS_COVE = "/props/curios/!!_curio_defaults/cove"
    PROPS_CURIOS_DEFAULTS_DARKESTDUNGEON = "/props/curios/!!_curio_defaults/darkestdungeon"
    PROPS_CURIOS_DEFAULTS_QUESTS = "/props/curios/!!_curio_defaults/quests"
    PROPS_CURIOS_DEFAULTS_RUINS = "/props/curios/!!_curio_defaults/ruins"
    PROPS_CURIOS_DEFAULTS_SHARED = "/props/curios/!!_curio_defaults/_shared"
    PROPS_CURIOS_DEFAULTS_WARRENS = "/props/curios/!!_curio_defaults/warrens"
    PROPS_CURIOS_DEFAULTS_WEALD = "/props/curios/!!_curio_defaults/weald"
    PROPS_CURIOS_ITEM_ANTIVENOM = "/props/curios/!!_item_interactions"
    PROPS_CURIOS_RESULT_CATEGORY = "/props/curios/!!_result_category"
    PROPS_OBSTACLES = "/props/obstacles"
    PROPS_TRAPS = "/props/traps"
    TOWN = "/town"
    UI = "/ui"
    UI_DUNGEON = "/ui/dungeon"
    UI_DUNGEON_SHARED = "/ui/dungeon/_shared"
    UI_SHARED = "/ui/shared"
    UI_TOWN = "/ui/town"
    VO = "/vo"
    VO_BAD = "/vo/bad"
    VO_GOOD = "/vo/good"
    VO_LOAD = "/vo/load"
    VO_NEUTRAL = "/vo/neutral"
    VO_TOWN = "/vo/town"
    VO_TOWN_EVENT = "/vo/town_event"
    VO_TUTORIAL = "/vo/tutorial"

    CUSTOM = "/custom"  # 不属于原版事件，仅用来存放音频，需要搭配 *.campaign.guid_overrides.json 文件使用


class BankSource(Enum):
    AMBIENCE = "ambience"
    EN = "en"
    GENERAL = "general"
    HERO = "hero"
    MUSIC = "music"
    PROPS = "props"
    RAID_SCREEN = "raid_screen"
    TITLE_SCREEN = "title_screen"
    TOWN = "town"
    UI = "ui"
    VOICEOVER = "voiceover"
    OTHERS = "others"  # 其他没弄明白的统一放在这里
